#!/usr/bin/env python3
"""V34 source. Low-r reuses the exact R45 model. High-r uses the declared
r>k source, a closed sign outer domain, and Appendix A §8 necessities.
No model generated by this file is a completed proof without a complete tree.
"""
from pathlib import Path
import importlib.util,json,math,argparse
import sympy as s
ROOT=Path(__file__).resolve().parent
R=s.Rational
# The endpoint K=2 is used only as a CLOSED OUTER bound for actual k>2 sources.
# All formulae are division-free there, and every source still has k>2.
def base_module():
    src=(ROOT/'reference/r45_build_model.py').read_text()
    old='assert 2<K<=J<=R(43,20)'
    assert src.count(old)==1
    namespace={'__name__':'v34_endpoint_extended_base','__file__':str(ROOT/'reference/r45_build_model.py')}
    exec(compile(src.replace(old,'assert 2<=K<=J<=R(43,20)'),namespace['__file__'],'exec'),namespace)
    return namespace
BASE=base_module()

def encode(vs,polys):
    rr=[(label,s.Poly(s.expand(expr),*vs)) for label,expr in polys]
    rr=[(label,p) for label,p in rr if not p.is_zero]
    monos=sorted({m for _,p in rr for m,_ in p.terms() if sum(m)==2})
    pairs=[[i for i,a in enumerate(m) for _ in range(a)] for m in monos]
    pos={m:len(vs)+i for i,m in enumerate(monos)}
    rows=[]
    for label,p in rr:
        co=[s.S(0)]*(len(vs)+len(monos));rhs=s.S(0)
        for m,val in p.terms():
            d=sum(m)
            if d==0:rhs=val
            elif d==1:co[m.index(1)]=-val
            elif d==2:co[pos[m]]=-val
            else:raise ValueError('nonquadratic row '+label)
        den=math.lcm(*[int(z.q) for z in co+[rhs]])
        vals=[int(z*den) for z in co+[rhs]];g=math.gcd(*vals);vals=[v//g for v in vals]
        if max(map(abs,vals))>=2**62:raise ValueError('row coefficient outside frozen format')
        rows.append({'name':label,'coefficients':vals[:-1],'rhs':vals[-1],
                     'polynomial':str(p.as_expr()),'positive_scale':str(R(den,g))})
    return pairs,rows

def make_model(K,J,typ,branch='low'):
    K,J=R(K),R(J)
    if not (2<=K<J<=R(21,10)):raise ValueError('V34 range requires 2 <= K < J <= 2.1')
    data=BASE['make_model'](K,J,typ,True,False)
    vs=tuple(s.Symbol(n) for n in data['variables']);env=dict(zip(data['variables'],vs))
    data['source_version']='V34_2026-09-08'
    data['branch']=branch
    data['actual_k_gt_2']=True
    if branch=='low':
        data['actual_r_relation']='r<=k'
        return data
    if branch!='high':raise ValueError(branch)
    k,r,w,A,B,c,d,p=[env[n] for n in ('k','r','w','A','B','c','d','p')]
    polys=[(row['name'],s.sympify(row['polynomial'],locals=env)) for row in data['rows'] if row['name']!='low_r']
    polys += [('high_r_outer',r-k),('high_rBc',k-B-r),('high_rAc',k*(1+c)-r),
              ('high_rAd',k*(1+d)-r),('high_gap_B',2*k-r+w-B),
              ('high_rank_product',-J*d*B-(r-k)**2),
              ('high_rank_symmetric',-J*c*A-(r-k)**2)]
    # r upper envelope tangents inherited with exact corrected intercepts.
    polys += [('r_tangent_1',R(6075,1024)-R(15,16)*k-r),
              ('r_tangent_2',R(972,125)-R(9,5)*k-r),
              ('r_tangent_3',R(1225,128)-R(21,8)*k-r)]
    data['pairs'],data['rows']=encode(vs,polys)
    data['low_r']=False
    data['actual_r_relation']='r>k (closed outer r>=k with A,B<=0,c,d>=0)'
    den=data['root_denominator'];lo,hi=data['root_numerators']
    rhi=min(R(4), K*(3+BASE['sqrt_bounds'](9-4*K)[1])/2,2*J)
    lo[1]=int(s.floor(max(K,R(data['target'])/2)*den))
    hi[1]=int(s.ceiling(rhi*den));hi[2]=int(s.ceiling((rhi-R(data['target']))*den))
    hi[4]=0;lo[5]=0;lo[6]=0
    if not all(a<b for a,b in zip(lo,hi)):raise ValueError('empty/fixed root must be handled explicitly')
    return data

def headers(data,path):
    BASE['headers'](data,path)
    with (Path(path)/'mc_exact_model.hpp').open('a') as f:
        f.write('constexpr int HEAD_TYPE='+str(1 if data['type']=='I' else 2)+';\n')

def main():
    ap=argparse.ArgumentParser();ap.add_argument('--K',required=True);ap.add_argument('--J',required=True)
    ap.add_argument('--type',required=True,choices=['I','II']);ap.add_argument('--branch',choices=['low','high'],required=True)
    ap.add_argument('--out',type=Path,required=True);a=ap.parse_args()
    data=make_model(a.K,a.J,a.type,a.branch);headers(data,a.out)
    (a.out/'scope.json').write_text(json.dumps({k:data[k] for k in ('K','J','type','branch','target','actual_k_gt_2','actual_r_relation')},indent=2)+'\n')
    print(json.dumps({'scope':json.loads((a.out/'scope.json').read_text()),'variables':len(data['variables']),'products':len(data['pairs']),'rows':len(data['rows'])}))
if __name__=='__main__':main()
