/-
D54 — the 64-vertex reduction for the sharp `3 × 3` cube bound.

**Generated by `scripts/d54_gen_vertex.py`; do not edit by hand.**  The generation is
reproducible and the emitted proof is checked by Lean: every leaf closes
`abs_det_le_minor_sum` with a `norm_num` evaluation of the three concrete `2 × 2`
cofactors of row `0` at a sign vertex of rows `1`, `2`.  No `native_decide`, no
`decide`, no table of pre-computed answers, no project axiom.

`abs_det_le_four` is the card's item 1; `abs_det_le_four_sharp` records that `4` is
attained, so the bound is sharp for the fixed cube.
-/
import Rho5.Shared.MinorThreeBound.Core

namespace Rho5.MinorThreeBound

open Matrix

/-- **Item 1 (reduction).**  Pushing the six entries of rows `1`, `2` of a cube matrix
to the endpoints never decreases `|det|`, and at each of the `64` sign vertices the
cofactor sum of row `0` is at most `4`. -/
theorem abs_det_le_four (K : Matrix (Fin 3) (Fin 3) ℝ) (h : ∀ a b, |K a b| ≤ 1) :
    |K.det| ≤ 4 := by
  have hsroot := abs_det_le_max_endpoints (K) 1 0 (h)
  refine hsroot.trans (max_le ?_ ?_)
  · -- entry (1, 0) := -1   [m]
    have hsm := abs_det_le_max_endpoints (setEntry (K) 1 0 (-1)) 1 1 (abs_setEntry_le (K) 1 0 (-1) (by norm_num) (h))
    refine hsm.trans (max_le ?_ ?_)
    · -- entry (1, 1) := -1   [m/m]
      have hsmm := abs_det_le_max_endpoints (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (abs_setEntry_le (setEntry (K) 1 0 (-1)) 1 1 (-1) (by norm_num) (abs_setEntry_le (K) 1 0 (-1) (by norm_num) (h)))
      refine hsmm.trans (max_le ?_ ?_)
      · -- entry (1, 2) := -1   [m/m/m]
        have hsmmm := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (-1)) 2 0 (abs_setEntry_le (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (-1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (-1)) 1 1 (-1) (by norm_num) (abs_setEntry_le (K) 1 0 (-1) (by norm_num) (h))))
        refine hsmmm.trans (max_le ?_ ?_)
        · -- entry (2, 0) := -1   [m/m/m/m]
          have hsmmmm := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (-1)) 2 0 (-1)) 2 1 (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (-1)) 2 0 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (-1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (-1)) 1 1 (-1) (by norm_num) (abs_setEntry_le (K) 1 0 (-1) (by norm_num) (h)))))
          refine hsmmmm.trans (max_le ?_ ?_)
          · -- entry (2, 1) := -1   [m/m/m/m/m]
            have hsmmmmm := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (-1)) 2 0 (-1)) 2 1 (-1)) 2 2 (abs_setEntry_le (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (-1)) 2 0 (-1)) 2 1 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (-1)) 2 0 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (-1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (-1)) 1 1 (-1) (by norm_num) (abs_setEntry_le (K) 1 0 (-1) (by norm_num) (h))))))
            refine hsmmmmm.trans (max_le ?_ ?_)
            · -- entry (2, 2) := -1   [m/m/m/m/m/m]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
            · -- entry (2, 2) := 1   [m/m/m/m/m/p]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
          · -- entry (2, 1) := 1   [m/m/m/m/p]
            have hsmmmmp := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (-1)) 2 0 (-1)) 2 1 (1)) 2 2 (abs_setEntry_le (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (-1)) 2 0 (-1)) 2 1 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (-1)) 2 0 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (-1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (-1)) 1 1 (-1) (by norm_num) (abs_setEntry_le (K) 1 0 (-1) (by norm_num) (h))))))
            refine hsmmmmp.trans (max_le ?_ ?_)
            · -- entry (2, 2) := -1   [m/m/m/m/p/m]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
            · -- entry (2, 2) := 1   [m/m/m/m/p/p]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
        · -- entry (2, 0) := 1   [m/m/m/p]
          have hsmmmp := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (-1)) 2 0 (1)) 2 1 (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (-1)) 2 0 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (-1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (-1)) 1 1 (-1) (by norm_num) (abs_setEntry_le (K) 1 0 (-1) (by norm_num) (h)))))
          refine hsmmmp.trans (max_le ?_ ?_)
          · -- entry (2, 1) := -1   [m/m/m/p/m]
            have hsmmmpm := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (-1)) 2 0 (1)) 2 1 (-1)) 2 2 (abs_setEntry_le (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (-1)) 2 0 (1)) 2 1 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (-1)) 2 0 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (-1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (-1)) 1 1 (-1) (by norm_num) (abs_setEntry_le (K) 1 0 (-1) (by norm_num) (h))))))
            refine hsmmmpm.trans (max_le ?_ ?_)
            · -- entry (2, 2) := -1   [m/m/m/p/m/m]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
            · -- entry (2, 2) := 1   [m/m/m/p/m/p]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
          · -- entry (2, 1) := 1   [m/m/m/p/p]
            have hsmmmpp := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (-1)) 2 0 (1)) 2 1 (1)) 2 2 (abs_setEntry_le (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (-1)) 2 0 (1)) 2 1 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (-1)) 2 0 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (-1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (-1)) 1 1 (-1) (by norm_num) (abs_setEntry_le (K) 1 0 (-1) (by norm_num) (h))))))
            refine hsmmmpp.trans (max_le ?_ ?_)
            · -- entry (2, 2) := -1   [m/m/m/p/p/m]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
            · -- entry (2, 2) := 1   [m/m/m/p/p/p]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
      · -- entry (1, 2) := 1   [m/m/p]
        have hsmmp := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (1)) 2 0 (abs_setEntry_le (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (-1)) 1 1 (-1) (by norm_num) (abs_setEntry_le (K) 1 0 (-1) (by norm_num) (h))))
        refine hsmmp.trans (max_le ?_ ?_)
        · -- entry (2, 0) := -1   [m/m/p/m]
          have hsmmpm := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (1)) 2 0 (-1)) 2 1 (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (1)) 2 0 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (-1)) 1 1 (-1) (by norm_num) (abs_setEntry_le (K) 1 0 (-1) (by norm_num) (h)))))
          refine hsmmpm.trans (max_le ?_ ?_)
          · -- entry (2, 1) := -1   [m/m/p/m/m]
            have hsmmpmm := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (1)) 2 0 (-1)) 2 1 (-1)) 2 2 (abs_setEntry_le (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (1)) 2 0 (-1)) 2 1 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (1)) 2 0 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (-1)) 1 1 (-1) (by norm_num) (abs_setEntry_le (K) 1 0 (-1) (by norm_num) (h))))))
            refine hsmmpmm.trans (max_le ?_ ?_)
            · -- entry (2, 2) := -1   [m/m/p/m/m/m]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
            · -- entry (2, 2) := 1   [m/m/p/m/m/p]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
          · -- entry (2, 1) := 1   [m/m/p/m/p]
            have hsmmpmp := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (1)) 2 0 (-1)) 2 1 (1)) 2 2 (abs_setEntry_le (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (1)) 2 0 (-1)) 2 1 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (1)) 2 0 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (-1)) 1 1 (-1) (by norm_num) (abs_setEntry_le (K) 1 0 (-1) (by norm_num) (h))))))
            refine hsmmpmp.trans (max_le ?_ ?_)
            · -- entry (2, 2) := -1   [m/m/p/m/p/m]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
            · -- entry (2, 2) := 1   [m/m/p/m/p/p]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
        · -- entry (2, 0) := 1   [m/m/p/p]
          have hsmmpp := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (1)) 2 0 (1)) 2 1 (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (1)) 2 0 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (-1)) 1 1 (-1) (by norm_num) (abs_setEntry_le (K) 1 0 (-1) (by norm_num) (h)))))
          refine hsmmpp.trans (max_le ?_ ?_)
          · -- entry (2, 1) := -1   [m/m/p/p/m]
            have hsmmppm := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (1)) 2 0 (1)) 2 1 (-1)) 2 2 (abs_setEntry_le (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (1)) 2 0 (1)) 2 1 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (1)) 2 0 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (-1)) 1 1 (-1) (by norm_num) (abs_setEntry_le (K) 1 0 (-1) (by norm_num) (h))))))
            refine hsmmppm.trans (max_le ?_ ?_)
            · -- entry (2, 2) := -1   [m/m/p/p/m/m]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
            · -- entry (2, 2) := 1   [m/m/p/p/m/p]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
          · -- entry (2, 1) := 1   [m/m/p/p/p]
            have hsmmppp := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (1)) 2 0 (1)) 2 1 (1)) 2 2 (abs_setEntry_le (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (1)) 2 0 (1)) 2 1 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (1)) 2 0 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (-1)) 1 1 (-1)) 1 2 (1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (-1)) 1 1 (-1) (by norm_num) (abs_setEntry_le (K) 1 0 (-1) (by norm_num) (h))))))
            refine hsmmppp.trans (max_le ?_ ?_)
            · -- entry (2, 2) := -1   [m/m/p/p/p/m]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
            · -- entry (2, 2) := 1   [m/m/p/p/p/p]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
    · -- entry (1, 1) := 1   [m/p]
      have hsmp := abs_det_le_max_endpoints (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (abs_setEntry_le (setEntry (K) 1 0 (-1)) 1 1 (1) (by norm_num) (abs_setEntry_le (K) 1 0 (-1) (by norm_num) (h)))
      refine hsmp.trans (max_le ?_ ?_)
      · -- entry (1, 2) := -1   [m/p/m]
        have hsmpm := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (-1)) 2 0 (abs_setEntry_le (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (-1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (-1)) 1 1 (1) (by norm_num) (abs_setEntry_le (K) 1 0 (-1) (by norm_num) (h))))
        refine hsmpm.trans (max_le ?_ ?_)
        · -- entry (2, 0) := -1   [m/p/m/m]
          have hsmpmm := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (-1)) 2 0 (-1)) 2 1 (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (-1)) 2 0 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (-1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (-1)) 1 1 (1) (by norm_num) (abs_setEntry_le (K) 1 0 (-1) (by norm_num) (h)))))
          refine hsmpmm.trans (max_le ?_ ?_)
          · -- entry (2, 1) := -1   [m/p/m/m/m]
            have hsmpmmm := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (-1)) 2 0 (-1)) 2 1 (-1)) 2 2 (abs_setEntry_le (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (-1)) 2 0 (-1)) 2 1 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (-1)) 2 0 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (-1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (-1)) 1 1 (1) (by norm_num) (abs_setEntry_le (K) 1 0 (-1) (by norm_num) (h))))))
            refine hsmpmmm.trans (max_le ?_ ?_)
            · -- entry (2, 2) := -1   [m/p/m/m/m/m]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
            · -- entry (2, 2) := 1   [m/p/m/m/m/p]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
          · -- entry (2, 1) := 1   [m/p/m/m/p]
            have hsmpmmp := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (-1)) 2 0 (-1)) 2 1 (1)) 2 2 (abs_setEntry_le (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (-1)) 2 0 (-1)) 2 1 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (-1)) 2 0 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (-1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (-1)) 1 1 (1) (by norm_num) (abs_setEntry_le (K) 1 0 (-1) (by norm_num) (h))))))
            refine hsmpmmp.trans (max_le ?_ ?_)
            · -- entry (2, 2) := -1   [m/p/m/m/p/m]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
            · -- entry (2, 2) := 1   [m/p/m/m/p/p]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
        · -- entry (2, 0) := 1   [m/p/m/p]
          have hsmpmp := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (-1)) 2 0 (1)) 2 1 (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (-1)) 2 0 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (-1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (-1)) 1 1 (1) (by norm_num) (abs_setEntry_le (K) 1 0 (-1) (by norm_num) (h)))))
          refine hsmpmp.trans (max_le ?_ ?_)
          · -- entry (2, 1) := -1   [m/p/m/p/m]
            have hsmpmpm := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (-1)) 2 0 (1)) 2 1 (-1)) 2 2 (abs_setEntry_le (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (-1)) 2 0 (1)) 2 1 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (-1)) 2 0 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (-1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (-1)) 1 1 (1) (by norm_num) (abs_setEntry_le (K) 1 0 (-1) (by norm_num) (h))))))
            refine hsmpmpm.trans (max_le ?_ ?_)
            · -- entry (2, 2) := -1   [m/p/m/p/m/m]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
            · -- entry (2, 2) := 1   [m/p/m/p/m/p]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
          · -- entry (2, 1) := 1   [m/p/m/p/p]
            have hsmpmpp := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (-1)) 2 0 (1)) 2 1 (1)) 2 2 (abs_setEntry_le (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (-1)) 2 0 (1)) 2 1 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (-1)) 2 0 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (-1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (-1)) 1 1 (1) (by norm_num) (abs_setEntry_le (K) 1 0 (-1) (by norm_num) (h))))))
            refine hsmpmpp.trans (max_le ?_ ?_)
            · -- entry (2, 2) := -1   [m/p/m/p/p/m]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
            · -- entry (2, 2) := 1   [m/p/m/p/p/p]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
      · -- entry (1, 2) := 1   [m/p/p]
        have hsmpp := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (1)) 2 0 (abs_setEntry_le (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (-1)) 1 1 (1) (by norm_num) (abs_setEntry_le (K) 1 0 (-1) (by norm_num) (h))))
        refine hsmpp.trans (max_le ?_ ?_)
        · -- entry (2, 0) := -1   [m/p/p/m]
          have hsmppm := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (1)) 2 0 (-1)) 2 1 (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (1)) 2 0 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (-1)) 1 1 (1) (by norm_num) (abs_setEntry_le (K) 1 0 (-1) (by norm_num) (h)))))
          refine hsmppm.trans (max_le ?_ ?_)
          · -- entry (2, 1) := -1   [m/p/p/m/m]
            have hsmppmm := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (1)) 2 0 (-1)) 2 1 (-1)) 2 2 (abs_setEntry_le (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (1)) 2 0 (-1)) 2 1 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (1)) 2 0 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (-1)) 1 1 (1) (by norm_num) (abs_setEntry_le (K) 1 0 (-1) (by norm_num) (h))))))
            refine hsmppmm.trans (max_le ?_ ?_)
            · -- entry (2, 2) := -1   [m/p/p/m/m/m]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
            · -- entry (2, 2) := 1   [m/p/p/m/m/p]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
          · -- entry (2, 1) := 1   [m/p/p/m/p]
            have hsmppmp := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (1)) 2 0 (-1)) 2 1 (1)) 2 2 (abs_setEntry_le (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (1)) 2 0 (-1)) 2 1 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (1)) 2 0 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (-1)) 1 1 (1) (by norm_num) (abs_setEntry_le (K) 1 0 (-1) (by norm_num) (h))))))
            refine hsmppmp.trans (max_le ?_ ?_)
            · -- entry (2, 2) := -1   [m/p/p/m/p/m]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
            · -- entry (2, 2) := 1   [m/p/p/m/p/p]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
        · -- entry (2, 0) := 1   [m/p/p/p]
          have hsmppp := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (1)) 2 0 (1)) 2 1 (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (1)) 2 0 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (-1)) 1 1 (1) (by norm_num) (abs_setEntry_le (K) 1 0 (-1) (by norm_num) (h)))))
          refine hsmppp.trans (max_le ?_ ?_)
          · -- entry (2, 1) := -1   [m/p/p/p/m]
            have hsmpppm := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (1)) 2 0 (1)) 2 1 (-1)) 2 2 (abs_setEntry_le (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (1)) 2 0 (1)) 2 1 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (1)) 2 0 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (-1)) 1 1 (1) (by norm_num) (abs_setEntry_le (K) 1 0 (-1) (by norm_num) (h))))))
            refine hsmpppm.trans (max_le ?_ ?_)
            · -- entry (2, 2) := -1   [m/p/p/p/m/m]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
            · -- entry (2, 2) := 1   [m/p/p/p/m/p]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
          · -- entry (2, 1) := 1   [m/p/p/p/p]
            have hsmpppp := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (1)) 2 0 (1)) 2 1 (1)) 2 2 (abs_setEntry_le (setEntry (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (1)) 2 0 (1)) 2 1 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (1)) 2 0 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (-1)) 1 1 (1)) 1 2 (1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (-1)) 1 1 (1) (by norm_num) (abs_setEntry_le (K) 1 0 (-1) (by norm_num) (h))))))
            refine hsmpppp.trans (max_le ?_ ?_)
            · -- entry (2, 2) := -1   [m/p/p/p/p/m]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
            · -- entry (2, 2) := 1   [m/p/p/p/p/p]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
  · -- entry (1, 0) := 1   [p]
    have hsp := abs_det_le_max_endpoints (setEntry (K) 1 0 (1)) 1 1 (abs_setEntry_le (K) 1 0 (1) (by norm_num) (h))
    refine hsp.trans (max_le ?_ ?_)
    · -- entry (1, 1) := -1   [p/m]
      have hspm := abs_det_le_max_endpoints (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (abs_setEntry_le (setEntry (K) 1 0 (1)) 1 1 (-1) (by norm_num) (abs_setEntry_le (K) 1 0 (1) (by norm_num) (h)))
      refine hspm.trans (max_le ?_ ?_)
      · -- entry (1, 2) := -1   [p/m/m]
        have hspmm := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (-1)) 2 0 (abs_setEntry_le (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (-1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (1)) 1 1 (-1) (by norm_num) (abs_setEntry_le (K) 1 0 (1) (by norm_num) (h))))
        refine hspmm.trans (max_le ?_ ?_)
        · -- entry (2, 0) := -1   [p/m/m/m]
          have hspmmm := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (-1)) 2 0 (-1)) 2 1 (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (-1)) 2 0 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (-1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (1)) 1 1 (-1) (by norm_num) (abs_setEntry_le (K) 1 0 (1) (by norm_num) (h)))))
          refine hspmmm.trans (max_le ?_ ?_)
          · -- entry (2, 1) := -1   [p/m/m/m/m]
            have hspmmmm := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (-1)) 2 0 (-1)) 2 1 (-1)) 2 2 (abs_setEntry_le (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (-1)) 2 0 (-1)) 2 1 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (-1)) 2 0 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (-1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (1)) 1 1 (-1) (by norm_num) (abs_setEntry_le (K) 1 0 (1) (by norm_num) (h))))))
            refine hspmmmm.trans (max_le ?_ ?_)
            · -- entry (2, 2) := -1   [p/m/m/m/m/m]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
            · -- entry (2, 2) := 1   [p/m/m/m/m/p]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
          · -- entry (2, 1) := 1   [p/m/m/m/p]
            have hspmmmp := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (-1)) 2 0 (-1)) 2 1 (1)) 2 2 (abs_setEntry_le (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (-1)) 2 0 (-1)) 2 1 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (-1)) 2 0 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (-1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (1)) 1 1 (-1) (by norm_num) (abs_setEntry_le (K) 1 0 (1) (by norm_num) (h))))))
            refine hspmmmp.trans (max_le ?_ ?_)
            · -- entry (2, 2) := -1   [p/m/m/m/p/m]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
            · -- entry (2, 2) := 1   [p/m/m/m/p/p]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
        · -- entry (2, 0) := 1   [p/m/m/p]
          have hspmmp := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (-1)) 2 0 (1)) 2 1 (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (-1)) 2 0 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (-1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (1)) 1 1 (-1) (by norm_num) (abs_setEntry_le (K) 1 0 (1) (by norm_num) (h)))))
          refine hspmmp.trans (max_le ?_ ?_)
          · -- entry (2, 1) := -1   [p/m/m/p/m]
            have hspmmpm := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (-1)) 2 0 (1)) 2 1 (-1)) 2 2 (abs_setEntry_le (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (-1)) 2 0 (1)) 2 1 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (-1)) 2 0 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (-1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (1)) 1 1 (-1) (by norm_num) (abs_setEntry_le (K) 1 0 (1) (by norm_num) (h))))))
            refine hspmmpm.trans (max_le ?_ ?_)
            · -- entry (2, 2) := -1   [p/m/m/p/m/m]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
            · -- entry (2, 2) := 1   [p/m/m/p/m/p]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
          · -- entry (2, 1) := 1   [p/m/m/p/p]
            have hspmmpp := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (-1)) 2 0 (1)) 2 1 (1)) 2 2 (abs_setEntry_le (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (-1)) 2 0 (1)) 2 1 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (-1)) 2 0 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (-1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (1)) 1 1 (-1) (by norm_num) (abs_setEntry_le (K) 1 0 (1) (by norm_num) (h))))))
            refine hspmmpp.trans (max_le ?_ ?_)
            · -- entry (2, 2) := -1   [p/m/m/p/p/m]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
            · -- entry (2, 2) := 1   [p/m/m/p/p/p]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
      · -- entry (1, 2) := 1   [p/m/p]
        have hspmp := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (1)) 2 0 (abs_setEntry_le (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (1)) 1 1 (-1) (by norm_num) (abs_setEntry_le (K) 1 0 (1) (by norm_num) (h))))
        refine hspmp.trans (max_le ?_ ?_)
        · -- entry (2, 0) := -1   [p/m/p/m]
          have hspmpm := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (1)) 2 0 (-1)) 2 1 (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (1)) 2 0 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (1)) 1 1 (-1) (by norm_num) (abs_setEntry_le (K) 1 0 (1) (by norm_num) (h)))))
          refine hspmpm.trans (max_le ?_ ?_)
          · -- entry (2, 1) := -1   [p/m/p/m/m]
            have hspmpmm := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (1)) 2 0 (-1)) 2 1 (-1)) 2 2 (abs_setEntry_le (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (1)) 2 0 (-1)) 2 1 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (1)) 2 0 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (1)) 1 1 (-1) (by norm_num) (abs_setEntry_le (K) 1 0 (1) (by norm_num) (h))))))
            refine hspmpmm.trans (max_le ?_ ?_)
            · -- entry (2, 2) := -1   [p/m/p/m/m/m]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
            · -- entry (2, 2) := 1   [p/m/p/m/m/p]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
          · -- entry (2, 1) := 1   [p/m/p/m/p]
            have hspmpmp := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (1)) 2 0 (-1)) 2 1 (1)) 2 2 (abs_setEntry_le (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (1)) 2 0 (-1)) 2 1 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (1)) 2 0 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (1)) 1 1 (-1) (by norm_num) (abs_setEntry_le (K) 1 0 (1) (by norm_num) (h))))))
            refine hspmpmp.trans (max_le ?_ ?_)
            · -- entry (2, 2) := -1   [p/m/p/m/p/m]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
            · -- entry (2, 2) := 1   [p/m/p/m/p/p]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
        · -- entry (2, 0) := 1   [p/m/p/p]
          have hspmpp := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (1)) 2 0 (1)) 2 1 (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (1)) 2 0 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (1)) 1 1 (-1) (by norm_num) (abs_setEntry_le (K) 1 0 (1) (by norm_num) (h)))))
          refine hspmpp.trans (max_le ?_ ?_)
          · -- entry (2, 1) := -1   [p/m/p/p/m]
            have hspmppm := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (1)) 2 0 (1)) 2 1 (-1)) 2 2 (abs_setEntry_le (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (1)) 2 0 (1)) 2 1 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (1)) 2 0 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (1)) 1 1 (-1) (by norm_num) (abs_setEntry_le (K) 1 0 (1) (by norm_num) (h))))))
            refine hspmppm.trans (max_le ?_ ?_)
            · -- entry (2, 2) := -1   [p/m/p/p/m/m]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
            · -- entry (2, 2) := 1   [p/m/p/p/m/p]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
          · -- entry (2, 1) := 1   [p/m/p/p/p]
            have hspmppp := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (1)) 2 0 (1)) 2 1 (1)) 2 2 (abs_setEntry_le (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (1)) 2 0 (1)) 2 1 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (1)) 2 0 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (1)) 1 1 (-1)) 1 2 (1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (1)) 1 1 (-1) (by norm_num) (abs_setEntry_le (K) 1 0 (1) (by norm_num) (h))))))
            refine hspmppp.trans (max_le ?_ ?_)
            · -- entry (2, 2) := -1   [p/m/p/p/p/m]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
            · -- entry (2, 2) := 1   [p/m/p/p/p/p]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
    · -- entry (1, 1) := 1   [p/p]
      have hspp := abs_det_le_max_endpoints (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (abs_setEntry_le (setEntry (K) 1 0 (1)) 1 1 (1) (by norm_num) (abs_setEntry_le (K) 1 0 (1) (by norm_num) (h)))
      refine hspp.trans (max_le ?_ ?_)
      · -- entry (1, 2) := -1   [p/p/m]
        have hsppm := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (-1)) 2 0 (abs_setEntry_le (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (-1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (1)) 1 1 (1) (by norm_num) (abs_setEntry_le (K) 1 0 (1) (by norm_num) (h))))
        refine hsppm.trans (max_le ?_ ?_)
        · -- entry (2, 0) := -1   [p/p/m/m]
          have hsppmm := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (-1)) 2 0 (-1)) 2 1 (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (-1)) 2 0 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (-1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (1)) 1 1 (1) (by norm_num) (abs_setEntry_le (K) 1 0 (1) (by norm_num) (h)))))
          refine hsppmm.trans (max_le ?_ ?_)
          · -- entry (2, 1) := -1   [p/p/m/m/m]
            have hsppmmm := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (-1)) 2 0 (-1)) 2 1 (-1)) 2 2 (abs_setEntry_le (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (-1)) 2 0 (-1)) 2 1 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (-1)) 2 0 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (-1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (1)) 1 1 (1) (by norm_num) (abs_setEntry_le (K) 1 0 (1) (by norm_num) (h))))))
            refine hsppmmm.trans (max_le ?_ ?_)
            · -- entry (2, 2) := -1   [p/p/m/m/m/m]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
            · -- entry (2, 2) := 1   [p/p/m/m/m/p]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
          · -- entry (2, 1) := 1   [p/p/m/m/p]
            have hsppmmp := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (-1)) 2 0 (-1)) 2 1 (1)) 2 2 (abs_setEntry_le (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (-1)) 2 0 (-1)) 2 1 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (-1)) 2 0 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (-1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (1)) 1 1 (1) (by norm_num) (abs_setEntry_le (K) 1 0 (1) (by norm_num) (h))))))
            refine hsppmmp.trans (max_le ?_ ?_)
            · -- entry (2, 2) := -1   [p/p/m/m/p/m]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
            · -- entry (2, 2) := 1   [p/p/m/m/p/p]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
        · -- entry (2, 0) := 1   [p/p/m/p]
          have hsppmp := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (-1)) 2 0 (1)) 2 1 (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (-1)) 2 0 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (-1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (1)) 1 1 (1) (by norm_num) (abs_setEntry_le (K) 1 0 (1) (by norm_num) (h)))))
          refine hsppmp.trans (max_le ?_ ?_)
          · -- entry (2, 1) := -1   [p/p/m/p/m]
            have hsppmpm := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (-1)) 2 0 (1)) 2 1 (-1)) 2 2 (abs_setEntry_le (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (-1)) 2 0 (1)) 2 1 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (-1)) 2 0 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (-1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (1)) 1 1 (1) (by norm_num) (abs_setEntry_le (K) 1 0 (1) (by norm_num) (h))))))
            refine hsppmpm.trans (max_le ?_ ?_)
            · -- entry (2, 2) := -1   [p/p/m/p/m/m]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
            · -- entry (2, 2) := 1   [p/p/m/p/m/p]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
          · -- entry (2, 1) := 1   [p/p/m/p/p]
            have hsppmpp := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (-1)) 2 0 (1)) 2 1 (1)) 2 2 (abs_setEntry_le (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (-1)) 2 0 (1)) 2 1 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (-1)) 2 0 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (-1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (1)) 1 1 (1) (by norm_num) (abs_setEntry_le (K) 1 0 (1) (by norm_num) (h))))))
            refine hsppmpp.trans (max_le ?_ ?_)
            · -- entry (2, 2) := -1   [p/p/m/p/p/m]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
            · -- entry (2, 2) := 1   [p/p/m/p/p/p]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
      · -- entry (1, 2) := 1   [p/p/p]
        have hsppp := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (1)) 2 0 (abs_setEntry_le (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (1)) 1 1 (1) (by norm_num) (abs_setEntry_le (K) 1 0 (1) (by norm_num) (h))))
        refine hsppp.trans (max_le ?_ ?_)
        · -- entry (2, 0) := -1   [p/p/p/m]
          have hspppm := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (1)) 2 0 (-1)) 2 1 (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (1)) 2 0 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (1)) 1 1 (1) (by norm_num) (abs_setEntry_le (K) 1 0 (1) (by norm_num) (h)))))
          refine hspppm.trans (max_le ?_ ?_)
          · -- entry (2, 1) := -1   [p/p/p/m/m]
            have hspppmm := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (1)) 2 0 (-1)) 2 1 (-1)) 2 2 (abs_setEntry_le (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (1)) 2 0 (-1)) 2 1 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (1)) 2 0 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (1)) 1 1 (1) (by norm_num) (abs_setEntry_le (K) 1 0 (1) (by norm_num) (h))))))
            refine hspppmm.trans (max_le ?_ ?_)
            · -- entry (2, 2) := -1   [p/p/p/m/m/m]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
            · -- entry (2, 2) := 1   [p/p/p/m/m/p]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
          · -- entry (2, 1) := 1   [p/p/p/m/p]
            have hspppmp := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (1)) 2 0 (-1)) 2 1 (1)) 2 2 (abs_setEntry_le (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (1)) 2 0 (-1)) 2 1 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (1)) 2 0 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (1)) 1 1 (1) (by norm_num) (abs_setEntry_le (K) 1 0 (1) (by norm_num) (h))))))
            refine hspppmp.trans (max_le ?_ ?_)
            · -- entry (2, 2) := -1   [p/p/p/m/p/m]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
            · -- entry (2, 2) := 1   [p/p/p/m/p/p]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
        · -- entry (2, 0) := 1   [p/p/p/p]
          have hspppp := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (1)) 2 0 (1)) 2 1 (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (1)) 2 0 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (1)) 1 1 (1) (by norm_num) (abs_setEntry_le (K) 1 0 (1) (by norm_num) (h)))))
          refine hspppp.trans (max_le ?_ ?_)
          · -- entry (2, 1) := -1   [p/p/p/p/m]
            have hsppppm := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (1)) 2 0 (1)) 2 1 (-1)) 2 2 (abs_setEntry_le (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (1)) 2 0 (1)) 2 1 (-1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (1)) 2 0 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (1)) 1 1 (1) (by norm_num) (abs_setEntry_le (K) 1 0 (1) (by norm_num) (h))))))
            refine hsppppm.trans (max_le ?_ ?_)
            · -- entry (2, 2) := -1   [p/p/p/p/m/m]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
            · -- entry (2, 2) := 1   [p/p/p/p/m/p]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
          · -- entry (2, 1) := 1   [p/p/p/p/p]
            have hsppppp := abs_det_le_max_endpoints (setEntry (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (1)) 2 0 (1)) 2 1 (1)) 2 2 (abs_setEntry_le (setEntry (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (1)) 2 0 (1)) 2 1 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (1)) 2 0 (1) (by norm_num) (abs_setEntry_le (setEntry (setEntry (K) 1 0 (1)) 1 1 (1)) 1 2 (1) (by norm_num) (abs_setEntry_le (setEntry (K) 1 0 (1)) 1 1 (1) (by norm_num) (abs_setEntry_le (K) 1 0 (1) (by norm_num) (h))))))
            refine hsppppp.trans (max_le ?_ ?_)
            · -- entry (2, 2) := -1   [p/p/p/p/p/m]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2
            · -- entry (2, 2) := 1   [p/p/p/p/p/p]
              refine (abs_det_le_minor_sum _ ?_ ?_ ?_).trans (by norm_num [setEntry])
              · simpa [setEntry] using h 0 0
              · simpa [setEntry] using h 0 1
              · simpa [setEntry] using h 0 2

/-- The sharpness witness, written as an explicit lambda so that no matrix notation
lemma is needed: the matrix `[[1,1,1],[1,1,-1],[1,-1,1]]`.  As in `setEntry`, the
guards are written on `Fin.val` so that they reduce definitionally. -/
def sharpK : Matrix (Fin 3) (Fin 3) ℝ :=
  fun i j =>
    if i.val = 0 ∧ j.val = 0 then 1 else if i.val = 0 ∧ j.val = 1 then 1
    else if i.val = 0 ∧ j.val = 2 then 1
    else if i.val = 1 ∧ j.val = 0 then 1 else if i.val = 1 ∧ j.val = 1 then 1
    else if i.val = 1 ∧ j.val = 2 then -1
    else if i.val = 2 ∧ j.val = 0 then 1 else if i.val = 2 ∧ j.val = 1 then -1 else 1

/-- Every entry of the witness is in the cube. -/
theorem sharpK_entry (i j : Fin 3) : |sharpK i j| ≤ 1 := by
  fin_cases i <;> fin_cases j <;> simp only [sharpK, Fin.isValue] <;> norm_num

/-- **Sharpness.**  The bound `4` is attained inside the cube, so item 1 is the sharp
constant for the fixed `3 × 3` cube (and not merely a convenient upper bound). -/
theorem abs_det_le_four_sharp :
    ∃ K : Matrix (Fin 3) (Fin 3) ℝ, (∀ i j, |K i j| ≤ 1) ∧ |K.det| = 4 := by
  refine ⟨sharpK, sharpK_entry, ?_⟩
  simp only [Matrix.det_fin_three, sharpK, Fin.isValue]
  norm_num

end Rho5.MinorThreeBound
