import Rho5.Shared.MainlineTreeCover.Tree
import Mathlib.Tactic.FinCases
import Mathlib.Data.Fintype.Fin

/-!
# The actual first seven splits of the V31 root

Generated by tools/generate_v31_prefix.py from V31_FIRST_PREFIX_SAMPLE.json.
Frozen input SHA256: 883ee574053f16c3b0923fee0429aad68f088282027fa713cedcbad3abfa142a
Archive SHA256: 733afdacfc1c87ea77b4cfdd864ec71d3df03cb43b1ed025e8df04fe777c1302
Model SHA256: 5fb91ced098b36174e1f307f543cf30872a075f262d477bc2bdb378b39aa94c5

Coordinate order: k r w A B c d p e be u0 u1 u2 x0 x1 x2 v0 v1 v2 q0 q1 q2.
The root numerators have common denominator 4800. Source tree records 1--7
are S 21, S 20, S 19, S 15, S 13, S 14, S 11 (bytes [0,35)).
The following C record is line 8 (bytes [35,194)); its safety is NOT proved here.
The next raw record is S 12 at byte 194 in the retained sibling 0000001.

False means left, true means right. All eight frontier boxes are retained.
Both children are closed and include their common cut plane. No disjointness,
terminal safety, matrix feasibility, full-root exclusion or growth bound is
claimed by this module. The source parser and provenance hashes are not Lean
theorems. Every endpoint identity and coverage assertion below is an ordinary
Lean proof about the displayed rational constants.
-/

namespace Rho5.Shared.MainlineTreeCover.V31Prefix

def rootLoNumerators : Fin 22 → ℤ := fun i =>
  match i.val with
  | 0 => 8816
  | 1 => 9918
  | 2 => -9600
  | 3 => -9600
  | 4 => -9600
  | 5 => 636
  | 6 => 318
  | 7 => 4959
  | 8 => 159
  | 9 => 159
  | 10 => 0
  | 11 => -4800
  | 12 => -4800
  | 13 => -4800
  | 14 => -4800
  | 15 => -4800
  | 16 => -4800
  | 17 => -4800
  | 18 => -4800
  | 19 => -9600
  | 20 => -9600
  | 21 => -9600
  | _ => 0

def rootHiNumerators : Fin 22 → ℤ := fun i =>
  match i.val with
  | 0 => 9600
  | 1 => 18882
  | 2 => -318
  | 3 => -636
  | 4 => -636
  | 5 => 4800
  | 6 => 4482
  | 7 => 9600
  | 8 => 4800
  | 9 => 4800
  | 10 => 4800
  | 11 => 4800
  | 12 => 4800
  | 13 => 4800
  | 14 => 4800
  | 15 => 4800
  | 16 => 4800
  | 17 => 4800
  | 18 => 4800
  | 19 => 9600
  | 20 => 9600
  | 21 => 9600
  | _ => 0

def root : Box 22 where
  lo := fun i =>
    match i.val with
    | 0 => (8816 : ℚ) / 4800
    | 1 => (9918 : ℚ) / 4800
    | 2 => (-9600 : ℚ) / 4800
    | 3 => (-9600 : ℚ) / 4800
    | 4 => (-9600 : ℚ) / 4800
    | 5 => (636 : ℚ) / 4800
    | 6 => (318 : ℚ) / 4800
    | 7 => (4959 : ℚ) / 4800
    | 8 => (159 : ℚ) / 4800
    | 9 => (159 : ℚ) / 4800
    | 10 => (0 : ℚ) / 4800
    | 11 => (-4800 : ℚ) / 4800
    | 12 => (-4800 : ℚ) / 4800
    | 13 => (-4800 : ℚ) / 4800
    | 14 => (-4800 : ℚ) / 4800
    | 15 => (-4800 : ℚ) / 4800
    | 16 => (-4800 : ℚ) / 4800
    | 17 => (-4800 : ℚ) / 4800
    | 18 => (-4800 : ℚ) / 4800
    | 19 => (-9600 : ℚ) / 4800
    | 20 => (-9600 : ℚ) / 4800
    | 21 => (-9600 : ℚ) / 4800
    | _ => 0
  hi := fun i =>
    match i.val with
    | 0 => (9600 : ℚ) / 4800
    | 1 => (18882 : ℚ) / 4800
    | 2 => (-318 : ℚ) / 4800
    | 3 => (-636 : ℚ) / 4800
    | 4 => (-636 : ℚ) / 4800
    | 5 => (4800 : ℚ) / 4800
    | 6 => (4482 : ℚ) / 4800
    | 7 => (9600 : ℚ) / 4800
    | 8 => (4800 : ℚ) / 4800
    | 9 => (4800 : ℚ) / 4800
    | 10 => (4800 : ℚ) / 4800
    | 11 => (4800 : ℚ) / 4800
    | 12 => (4800 : ℚ) / 4800
    | 13 => (4800 : ℚ) / 4800
    | 14 => (4800 : ℚ) / 4800
    | 15 => (4800 : ℚ) / 4800
    | 16 => (4800 : ℚ) / 4800
    | 17 => (4800 : ℚ) / 4800
    | 18 => (4800 : ℚ) / 4800
    | 19 => (9600 : ℚ) / 4800
    | 20 => (9600 : ℚ) / 4800
    | 21 => (9600 : ℚ) / 4800
    | _ => 0

/-- All 44 root endpoints are bound to the frozen 22-dimensional payload. -/
theorem root_endpoints (i : Fin 22) :
    root.lo i = (rootLoNumerators i : ℚ) / 4800 ∧
    root.hi i = (rootHiNumerators i : ℚ) / 4800 := by
  fin_cases i <;> first | rfl | norm_num [root, rootLoNumerators, rootHiNumerators]

def prefixAxes : List (Fin 22) := [21, 20, 19, 15, 13, 14, 11]

/-- Literal Fin indices have exactly the seven source values, with no wraparound. -/
theorem prefixAxes_values : prefixAxes.map Fin.val = [21, 20, 19, 15, 13, 14, 11] := by
  rfl

def spine0 : Box 22 := root

def spine1 : Box 22 := spine0.left (21 : Fin 22) (0 : ℚ)

def spine2 : Box 22 := spine1.left (20 : Fin 22) (0 : ℚ)

def spine3 : Box 22 := spine2.left (19 : Fin 22) (0 : ℚ)

def spine4 : Box 22 := spine3.left (15 : Fin 22) (0 : ℚ)

def spine5 : Box 22 := spine4.left (13 : Fin 22) (0 : ℚ)

def spine6 : Box 22 := spine5.left (14 : Fin 22) (0 : ℚ)

def spine7 : Box 22 := spine6.left (11 : Fin 22) (0 : ℚ)

/-- The actual prefix is a left spine with every right sibling still a leaf. -/
def prefixTree : Tree 22 :=
  (.split (21 : Fin 22) (0 : ℚ) (.split (20 : Fin 22) (0 : ℚ) (.split (19 : Fin 22) (0 : ℚ) (.split (15 : Fin 22) (0 : ℚ) (.split (13 : Fin 22) (0 : ℚ) (.split (14 : Fin 22) (0 : ℚ) (.split (11 : Fin 22) (0 : ℚ) (.leaf : Tree 22) .leaf) .leaf) .leaf) .leaf) .leaf) .leaf) .leaf)

theorem cut0_midpoint : spine0.midpoint (21 : Fin 22) = (0 : ℚ) := by
  change ((-9600 : ℚ) / 4800 + (9600 : ℚ) / 4800) / 2 = 0
  norm_num

theorem cut0_valid : spine0.ValidCut (21 : Fin 22) (0 : ℚ) := by
  change (-9600 : ℚ) / 4800 < 0 ∧ (0 : ℚ) < (9600 : ℚ) / 4800
  norm_num

theorem cut1_midpoint : spine1.midpoint (20 : Fin 22) = (0 : ℚ) := by
  change ((-9600 : ℚ) / 4800 + (9600 : ℚ) / 4800) / 2 = 0
  norm_num

theorem cut1_valid : spine1.ValidCut (20 : Fin 22) (0 : ℚ) := by
  change (-9600 : ℚ) / 4800 < 0 ∧ (0 : ℚ) < (9600 : ℚ) / 4800
  norm_num

theorem cut2_midpoint : spine2.midpoint (19 : Fin 22) = (0 : ℚ) := by
  change ((-9600 : ℚ) / 4800 + (9600 : ℚ) / 4800) / 2 = 0
  norm_num

theorem cut2_valid : spine2.ValidCut (19 : Fin 22) (0 : ℚ) := by
  change (-9600 : ℚ) / 4800 < 0 ∧ (0 : ℚ) < (9600 : ℚ) / 4800
  norm_num

theorem cut3_midpoint : spine3.midpoint (15 : Fin 22) = (0 : ℚ) := by
  change ((-4800 : ℚ) / 4800 + (4800 : ℚ) / 4800) / 2 = 0
  norm_num

theorem cut3_valid : spine3.ValidCut (15 : Fin 22) (0 : ℚ) := by
  change (-4800 : ℚ) / 4800 < 0 ∧ (0 : ℚ) < (4800 : ℚ) / 4800
  norm_num

theorem cut4_midpoint : spine4.midpoint (13 : Fin 22) = (0 : ℚ) := by
  change ((-4800 : ℚ) / 4800 + (4800 : ℚ) / 4800) / 2 = 0
  norm_num

theorem cut4_valid : spine4.ValidCut (13 : Fin 22) (0 : ℚ) := by
  change (-4800 : ℚ) / 4800 < 0 ∧ (0 : ℚ) < (4800 : ℚ) / 4800
  norm_num

theorem cut5_midpoint : spine5.midpoint (14 : Fin 22) = (0 : ℚ) := by
  change ((-4800 : ℚ) / 4800 + (4800 : ℚ) / 4800) / 2 = 0
  norm_num

theorem cut5_valid : spine5.ValidCut (14 : Fin 22) (0 : ℚ) := by
  change (-4800 : ℚ) / 4800 < 0 ∧ (0 : ℚ) < (4800 : ℚ) / 4800
  norm_num

theorem cut6_midpoint : spine6.midpoint (11 : Fin 22) = (0 : ℚ) := by
  change ((-4800 : ℚ) / 4800 + (4800 : ℚ) / 4800) / 2 = 0
  norm_num

theorem cut6_valid : spine6.ValidCut (11 : Fin 22) (0 : ℚ) := by
  change (-4800 : ℚ) / 4800 < 0 ∧ (0 : ℚ) < (4800 : ℚ) / 4800
  norm_num

theorem prefix_wellFormed : wellFormed root prefixTree := by
  exact ⟨cut0_valid.1, cut0_valid.2, ⟨cut1_valid.1, cut1_valid.2, ⟨cut2_valid.1, cut2_valid.2, ⟨cut3_valid.1, cut3_valid.2, ⟨cut4_valid.1, cut4_valid.2, ⟨cut5_valid.1, cut5_valid.2, ⟨cut6_valid.1, cut6_valid.2, True.intro, True.intro⟩, True.intro⟩, True.intro⟩, True.intro⟩, True.intro⟩, True.intro⟩, True.intro⟩

theorem prefix_seven_splits : nSplits prefixTree = 7 := by
  rfl

theorem prefix_eight_leaves : (leafBoxes root prefixTree).length = 8 := by
  rfl

/-- Preorder leaves use false for left and true for right, without omitting siblings. -/
theorem prefix_leafPaths : leafPaths prefixTree =
    [[false, false, false, false, false, false, false],
     [false, false, false, false, false, false, true],
     [false, false, false, false, false, true],
     [false, false, false, false, true],
     [false, false, false, true],
     [false, false, true],
     [false, true],
     [true]] := by
  rfl

/-- Independent full literal payload for frontier path `0000000`. -/

def actualLeafBox0 : Box 22 where
  lo := fun i =>
    match i.val with
    | 0 => (8816 : ℚ) / 4800
    | 1 => (9918 : ℚ) / 4800
    | 2 => (-9600 : ℚ) / 4800
    | 3 => (-9600 : ℚ) / 4800
    | 4 => (-9600 : ℚ) / 4800
    | 5 => (636 : ℚ) / 4800
    | 6 => (318 : ℚ) / 4800
    | 7 => (4959 : ℚ) / 4800
    | 8 => (159 : ℚ) / 4800
    | 9 => (159 : ℚ) / 4800
    | 10 => (0 : ℚ) / 4800
    | 11 => (-4800 : ℚ) / 4800
    | 12 => (-4800 : ℚ) / 4800
    | 13 => (-4800 : ℚ) / 4800
    | 14 => (-4800 : ℚ) / 4800
    | 15 => (-4800 : ℚ) / 4800
    | 16 => (-4800 : ℚ) / 4800
    | 17 => (-4800 : ℚ) / 4800
    | 18 => (-4800 : ℚ) / 4800
    | 19 => (-9600 : ℚ) / 4800
    | 20 => (-9600 : ℚ) / 4800
    | 21 => (-9600 : ℚ) / 4800
    | _ => 0
  hi := fun i =>
    match i.val with
    | 0 => (9600 : ℚ) / 4800
    | 1 => (18882 : ℚ) / 4800
    | 2 => (-318 : ℚ) / 4800
    | 3 => (-636 : ℚ) / 4800
    | 4 => (-636 : ℚ) / 4800
    | 5 => (4800 : ℚ) / 4800
    | 6 => (4482 : ℚ) / 4800
    | 7 => (9600 : ℚ) / 4800
    | 8 => (4800 : ℚ) / 4800
    | 9 => (4800 : ℚ) / 4800
    | 10 => (4800 : ℚ) / 4800
    | 11 => (0 : ℚ) / 4800
    | 12 => (4800 : ℚ) / 4800
    | 13 => (0 : ℚ) / 4800
    | 14 => (0 : ℚ) / 4800
    | 15 => (0 : ℚ) / 4800
    | 16 => (4800 : ℚ) / 4800
    | 17 => (4800 : ℚ) / 4800
    | 18 => (4800 : ℚ) / 4800
    | 19 => (0 : ℚ) / 4800
    | 20 => (0 : ℚ) / 4800
    | 21 => (0 : ℚ) / 4800
    | _ => 0

/-- Independent full literal payload for frontier path `0000001`. -/

def actualLeafBox1 : Box 22 where
  lo := fun i =>
    match i.val with
    | 0 => (8816 : ℚ) / 4800
    | 1 => (9918 : ℚ) / 4800
    | 2 => (-9600 : ℚ) / 4800
    | 3 => (-9600 : ℚ) / 4800
    | 4 => (-9600 : ℚ) / 4800
    | 5 => (636 : ℚ) / 4800
    | 6 => (318 : ℚ) / 4800
    | 7 => (4959 : ℚ) / 4800
    | 8 => (159 : ℚ) / 4800
    | 9 => (159 : ℚ) / 4800
    | 10 => (0 : ℚ) / 4800
    | 11 => (0 : ℚ) / 4800
    | 12 => (-4800 : ℚ) / 4800
    | 13 => (-4800 : ℚ) / 4800
    | 14 => (-4800 : ℚ) / 4800
    | 15 => (-4800 : ℚ) / 4800
    | 16 => (-4800 : ℚ) / 4800
    | 17 => (-4800 : ℚ) / 4800
    | 18 => (-4800 : ℚ) / 4800
    | 19 => (-9600 : ℚ) / 4800
    | 20 => (-9600 : ℚ) / 4800
    | 21 => (-9600 : ℚ) / 4800
    | _ => 0
  hi := fun i =>
    match i.val with
    | 0 => (9600 : ℚ) / 4800
    | 1 => (18882 : ℚ) / 4800
    | 2 => (-318 : ℚ) / 4800
    | 3 => (-636 : ℚ) / 4800
    | 4 => (-636 : ℚ) / 4800
    | 5 => (4800 : ℚ) / 4800
    | 6 => (4482 : ℚ) / 4800
    | 7 => (9600 : ℚ) / 4800
    | 8 => (4800 : ℚ) / 4800
    | 9 => (4800 : ℚ) / 4800
    | 10 => (4800 : ℚ) / 4800
    | 11 => (4800 : ℚ) / 4800
    | 12 => (4800 : ℚ) / 4800
    | 13 => (0 : ℚ) / 4800
    | 14 => (0 : ℚ) / 4800
    | 15 => (0 : ℚ) / 4800
    | 16 => (4800 : ℚ) / 4800
    | 17 => (4800 : ℚ) / 4800
    | 18 => (4800 : ℚ) / 4800
    | 19 => (0 : ℚ) / 4800
    | 20 => (0 : ℚ) / 4800
    | 21 => (0 : ℚ) / 4800
    | _ => 0

/-- Independent full literal payload for frontier path `000001`. -/

def actualLeafBox2 : Box 22 where
  lo := fun i =>
    match i.val with
    | 0 => (8816 : ℚ) / 4800
    | 1 => (9918 : ℚ) / 4800
    | 2 => (-9600 : ℚ) / 4800
    | 3 => (-9600 : ℚ) / 4800
    | 4 => (-9600 : ℚ) / 4800
    | 5 => (636 : ℚ) / 4800
    | 6 => (318 : ℚ) / 4800
    | 7 => (4959 : ℚ) / 4800
    | 8 => (159 : ℚ) / 4800
    | 9 => (159 : ℚ) / 4800
    | 10 => (0 : ℚ) / 4800
    | 11 => (-4800 : ℚ) / 4800
    | 12 => (-4800 : ℚ) / 4800
    | 13 => (-4800 : ℚ) / 4800
    | 14 => (0 : ℚ) / 4800
    | 15 => (-4800 : ℚ) / 4800
    | 16 => (-4800 : ℚ) / 4800
    | 17 => (-4800 : ℚ) / 4800
    | 18 => (-4800 : ℚ) / 4800
    | 19 => (-9600 : ℚ) / 4800
    | 20 => (-9600 : ℚ) / 4800
    | 21 => (-9600 : ℚ) / 4800
    | _ => 0
  hi := fun i =>
    match i.val with
    | 0 => (9600 : ℚ) / 4800
    | 1 => (18882 : ℚ) / 4800
    | 2 => (-318 : ℚ) / 4800
    | 3 => (-636 : ℚ) / 4800
    | 4 => (-636 : ℚ) / 4800
    | 5 => (4800 : ℚ) / 4800
    | 6 => (4482 : ℚ) / 4800
    | 7 => (9600 : ℚ) / 4800
    | 8 => (4800 : ℚ) / 4800
    | 9 => (4800 : ℚ) / 4800
    | 10 => (4800 : ℚ) / 4800
    | 11 => (4800 : ℚ) / 4800
    | 12 => (4800 : ℚ) / 4800
    | 13 => (0 : ℚ) / 4800
    | 14 => (4800 : ℚ) / 4800
    | 15 => (0 : ℚ) / 4800
    | 16 => (4800 : ℚ) / 4800
    | 17 => (4800 : ℚ) / 4800
    | 18 => (4800 : ℚ) / 4800
    | 19 => (0 : ℚ) / 4800
    | 20 => (0 : ℚ) / 4800
    | 21 => (0 : ℚ) / 4800
    | _ => 0

/-- Independent full literal payload for frontier path `00001`. -/

def actualLeafBox3 : Box 22 where
  lo := fun i =>
    match i.val with
    | 0 => (8816 : ℚ) / 4800
    | 1 => (9918 : ℚ) / 4800
    | 2 => (-9600 : ℚ) / 4800
    | 3 => (-9600 : ℚ) / 4800
    | 4 => (-9600 : ℚ) / 4800
    | 5 => (636 : ℚ) / 4800
    | 6 => (318 : ℚ) / 4800
    | 7 => (4959 : ℚ) / 4800
    | 8 => (159 : ℚ) / 4800
    | 9 => (159 : ℚ) / 4800
    | 10 => (0 : ℚ) / 4800
    | 11 => (-4800 : ℚ) / 4800
    | 12 => (-4800 : ℚ) / 4800
    | 13 => (0 : ℚ) / 4800
    | 14 => (-4800 : ℚ) / 4800
    | 15 => (-4800 : ℚ) / 4800
    | 16 => (-4800 : ℚ) / 4800
    | 17 => (-4800 : ℚ) / 4800
    | 18 => (-4800 : ℚ) / 4800
    | 19 => (-9600 : ℚ) / 4800
    | 20 => (-9600 : ℚ) / 4800
    | 21 => (-9600 : ℚ) / 4800
    | _ => 0
  hi := fun i =>
    match i.val with
    | 0 => (9600 : ℚ) / 4800
    | 1 => (18882 : ℚ) / 4800
    | 2 => (-318 : ℚ) / 4800
    | 3 => (-636 : ℚ) / 4800
    | 4 => (-636 : ℚ) / 4800
    | 5 => (4800 : ℚ) / 4800
    | 6 => (4482 : ℚ) / 4800
    | 7 => (9600 : ℚ) / 4800
    | 8 => (4800 : ℚ) / 4800
    | 9 => (4800 : ℚ) / 4800
    | 10 => (4800 : ℚ) / 4800
    | 11 => (4800 : ℚ) / 4800
    | 12 => (4800 : ℚ) / 4800
    | 13 => (4800 : ℚ) / 4800
    | 14 => (4800 : ℚ) / 4800
    | 15 => (0 : ℚ) / 4800
    | 16 => (4800 : ℚ) / 4800
    | 17 => (4800 : ℚ) / 4800
    | 18 => (4800 : ℚ) / 4800
    | 19 => (0 : ℚ) / 4800
    | 20 => (0 : ℚ) / 4800
    | 21 => (0 : ℚ) / 4800
    | _ => 0

/-- Independent full literal payload for frontier path `0001`. -/

def actualLeafBox4 : Box 22 where
  lo := fun i =>
    match i.val with
    | 0 => (8816 : ℚ) / 4800
    | 1 => (9918 : ℚ) / 4800
    | 2 => (-9600 : ℚ) / 4800
    | 3 => (-9600 : ℚ) / 4800
    | 4 => (-9600 : ℚ) / 4800
    | 5 => (636 : ℚ) / 4800
    | 6 => (318 : ℚ) / 4800
    | 7 => (4959 : ℚ) / 4800
    | 8 => (159 : ℚ) / 4800
    | 9 => (159 : ℚ) / 4800
    | 10 => (0 : ℚ) / 4800
    | 11 => (-4800 : ℚ) / 4800
    | 12 => (-4800 : ℚ) / 4800
    | 13 => (-4800 : ℚ) / 4800
    | 14 => (-4800 : ℚ) / 4800
    | 15 => (0 : ℚ) / 4800
    | 16 => (-4800 : ℚ) / 4800
    | 17 => (-4800 : ℚ) / 4800
    | 18 => (-4800 : ℚ) / 4800
    | 19 => (-9600 : ℚ) / 4800
    | 20 => (-9600 : ℚ) / 4800
    | 21 => (-9600 : ℚ) / 4800
    | _ => 0
  hi := fun i =>
    match i.val with
    | 0 => (9600 : ℚ) / 4800
    | 1 => (18882 : ℚ) / 4800
    | 2 => (-318 : ℚ) / 4800
    | 3 => (-636 : ℚ) / 4800
    | 4 => (-636 : ℚ) / 4800
    | 5 => (4800 : ℚ) / 4800
    | 6 => (4482 : ℚ) / 4800
    | 7 => (9600 : ℚ) / 4800
    | 8 => (4800 : ℚ) / 4800
    | 9 => (4800 : ℚ) / 4800
    | 10 => (4800 : ℚ) / 4800
    | 11 => (4800 : ℚ) / 4800
    | 12 => (4800 : ℚ) / 4800
    | 13 => (4800 : ℚ) / 4800
    | 14 => (4800 : ℚ) / 4800
    | 15 => (4800 : ℚ) / 4800
    | 16 => (4800 : ℚ) / 4800
    | 17 => (4800 : ℚ) / 4800
    | 18 => (4800 : ℚ) / 4800
    | 19 => (0 : ℚ) / 4800
    | 20 => (0 : ℚ) / 4800
    | 21 => (0 : ℚ) / 4800
    | _ => 0

/-- Independent full literal payload for frontier path `001`. -/

def actualLeafBox5 : Box 22 where
  lo := fun i =>
    match i.val with
    | 0 => (8816 : ℚ) / 4800
    | 1 => (9918 : ℚ) / 4800
    | 2 => (-9600 : ℚ) / 4800
    | 3 => (-9600 : ℚ) / 4800
    | 4 => (-9600 : ℚ) / 4800
    | 5 => (636 : ℚ) / 4800
    | 6 => (318 : ℚ) / 4800
    | 7 => (4959 : ℚ) / 4800
    | 8 => (159 : ℚ) / 4800
    | 9 => (159 : ℚ) / 4800
    | 10 => (0 : ℚ) / 4800
    | 11 => (-4800 : ℚ) / 4800
    | 12 => (-4800 : ℚ) / 4800
    | 13 => (-4800 : ℚ) / 4800
    | 14 => (-4800 : ℚ) / 4800
    | 15 => (-4800 : ℚ) / 4800
    | 16 => (-4800 : ℚ) / 4800
    | 17 => (-4800 : ℚ) / 4800
    | 18 => (-4800 : ℚ) / 4800
    | 19 => (0 : ℚ) / 4800
    | 20 => (-9600 : ℚ) / 4800
    | 21 => (-9600 : ℚ) / 4800
    | _ => 0
  hi := fun i =>
    match i.val with
    | 0 => (9600 : ℚ) / 4800
    | 1 => (18882 : ℚ) / 4800
    | 2 => (-318 : ℚ) / 4800
    | 3 => (-636 : ℚ) / 4800
    | 4 => (-636 : ℚ) / 4800
    | 5 => (4800 : ℚ) / 4800
    | 6 => (4482 : ℚ) / 4800
    | 7 => (9600 : ℚ) / 4800
    | 8 => (4800 : ℚ) / 4800
    | 9 => (4800 : ℚ) / 4800
    | 10 => (4800 : ℚ) / 4800
    | 11 => (4800 : ℚ) / 4800
    | 12 => (4800 : ℚ) / 4800
    | 13 => (4800 : ℚ) / 4800
    | 14 => (4800 : ℚ) / 4800
    | 15 => (4800 : ℚ) / 4800
    | 16 => (4800 : ℚ) / 4800
    | 17 => (4800 : ℚ) / 4800
    | 18 => (4800 : ℚ) / 4800
    | 19 => (9600 : ℚ) / 4800
    | 20 => (0 : ℚ) / 4800
    | 21 => (0 : ℚ) / 4800
    | _ => 0

/-- Independent full literal payload for frontier path `01`. -/

def actualLeafBox6 : Box 22 where
  lo := fun i =>
    match i.val with
    | 0 => (8816 : ℚ) / 4800
    | 1 => (9918 : ℚ) / 4800
    | 2 => (-9600 : ℚ) / 4800
    | 3 => (-9600 : ℚ) / 4800
    | 4 => (-9600 : ℚ) / 4800
    | 5 => (636 : ℚ) / 4800
    | 6 => (318 : ℚ) / 4800
    | 7 => (4959 : ℚ) / 4800
    | 8 => (159 : ℚ) / 4800
    | 9 => (159 : ℚ) / 4800
    | 10 => (0 : ℚ) / 4800
    | 11 => (-4800 : ℚ) / 4800
    | 12 => (-4800 : ℚ) / 4800
    | 13 => (-4800 : ℚ) / 4800
    | 14 => (-4800 : ℚ) / 4800
    | 15 => (-4800 : ℚ) / 4800
    | 16 => (-4800 : ℚ) / 4800
    | 17 => (-4800 : ℚ) / 4800
    | 18 => (-4800 : ℚ) / 4800
    | 19 => (-9600 : ℚ) / 4800
    | 20 => (0 : ℚ) / 4800
    | 21 => (-9600 : ℚ) / 4800
    | _ => 0
  hi := fun i =>
    match i.val with
    | 0 => (9600 : ℚ) / 4800
    | 1 => (18882 : ℚ) / 4800
    | 2 => (-318 : ℚ) / 4800
    | 3 => (-636 : ℚ) / 4800
    | 4 => (-636 : ℚ) / 4800
    | 5 => (4800 : ℚ) / 4800
    | 6 => (4482 : ℚ) / 4800
    | 7 => (9600 : ℚ) / 4800
    | 8 => (4800 : ℚ) / 4800
    | 9 => (4800 : ℚ) / 4800
    | 10 => (4800 : ℚ) / 4800
    | 11 => (4800 : ℚ) / 4800
    | 12 => (4800 : ℚ) / 4800
    | 13 => (4800 : ℚ) / 4800
    | 14 => (4800 : ℚ) / 4800
    | 15 => (4800 : ℚ) / 4800
    | 16 => (4800 : ℚ) / 4800
    | 17 => (4800 : ℚ) / 4800
    | 18 => (4800 : ℚ) / 4800
    | 19 => (9600 : ℚ) / 4800
    | 20 => (9600 : ℚ) / 4800
    | 21 => (0 : ℚ) / 4800
    | _ => 0

/-- Independent full literal payload for frontier path `1`. -/

def actualLeafBox7 : Box 22 where
  lo := fun i =>
    match i.val with
    | 0 => (8816 : ℚ) / 4800
    | 1 => (9918 : ℚ) / 4800
    | 2 => (-9600 : ℚ) / 4800
    | 3 => (-9600 : ℚ) / 4800
    | 4 => (-9600 : ℚ) / 4800
    | 5 => (636 : ℚ) / 4800
    | 6 => (318 : ℚ) / 4800
    | 7 => (4959 : ℚ) / 4800
    | 8 => (159 : ℚ) / 4800
    | 9 => (159 : ℚ) / 4800
    | 10 => (0 : ℚ) / 4800
    | 11 => (-4800 : ℚ) / 4800
    | 12 => (-4800 : ℚ) / 4800
    | 13 => (-4800 : ℚ) / 4800
    | 14 => (-4800 : ℚ) / 4800
    | 15 => (-4800 : ℚ) / 4800
    | 16 => (-4800 : ℚ) / 4800
    | 17 => (-4800 : ℚ) / 4800
    | 18 => (-4800 : ℚ) / 4800
    | 19 => (-9600 : ℚ) / 4800
    | 20 => (-9600 : ℚ) / 4800
    | 21 => (0 : ℚ) / 4800
    | _ => 0
  hi := fun i =>
    match i.val with
    | 0 => (9600 : ℚ) / 4800
    | 1 => (18882 : ℚ) / 4800
    | 2 => (-318 : ℚ) / 4800
    | 3 => (-636 : ℚ) / 4800
    | 4 => (-636 : ℚ) / 4800
    | 5 => (4800 : ℚ) / 4800
    | 6 => (4482 : ℚ) / 4800
    | 7 => (9600 : ℚ) / 4800
    | 8 => (4800 : ℚ) / 4800
    | 9 => (4800 : ℚ) / 4800
    | 10 => (4800 : ℚ) / 4800
    | 11 => (4800 : ℚ) / 4800
    | 12 => (4800 : ℚ) / 4800
    | 13 => (4800 : ℚ) / 4800
    | 14 => (4800 : ℚ) / 4800
    | 15 => (4800 : ℚ) / 4800
    | 16 => (4800 : ℚ) / 4800
    | 17 => (4800 : ℚ) / 4800
    | 18 => (4800 : ℚ) / 4800
    | 19 => (9600 : ℚ) / 4800
    | 20 => (9600 : ℚ) / 4800
    | 21 => (9600 : ℚ) / 4800
    | _ => 0

/-- Both endpoint functions are compared on every one of the 22 coordinates. -/
theorem inheritedBox0_eq_literal :
    spine7 = actualLeafBox0 := by
  apply Box.ext
  · intro i
    fin_cases i <;> first | rfl | exact (zero_div (4800 : ℚ)).symm
  · intro i
    fin_cases i <;> first | rfl | exact (zero_div (4800 : ℚ)).symm

/-- Both endpoint functions are compared on every one of the 22 coordinates. -/
theorem inheritedBox1_eq_literal :
    spine6.right (11 : Fin 22) (0 : ℚ) = actualLeafBox1 := by
  apply Box.ext
  · intro i
    fin_cases i <;> first | rfl | exact (zero_div (4800 : ℚ)).symm
  · intro i
    fin_cases i <;> first | rfl | exact (zero_div (4800 : ℚ)).symm

/-- Both endpoint functions are compared on every one of the 22 coordinates. -/
theorem inheritedBox2_eq_literal :
    spine5.right (14 : Fin 22) (0 : ℚ) = actualLeafBox2 := by
  apply Box.ext
  · intro i
    fin_cases i <;> first | rfl | exact (zero_div (4800 : ℚ)).symm
  · intro i
    fin_cases i <;> first | rfl | exact (zero_div (4800 : ℚ)).symm

/-- Both endpoint functions are compared on every one of the 22 coordinates. -/
theorem inheritedBox3_eq_literal :
    spine4.right (13 : Fin 22) (0 : ℚ) = actualLeafBox3 := by
  apply Box.ext
  · intro i
    fin_cases i <;> first | rfl | exact (zero_div (4800 : ℚ)).symm
  · intro i
    fin_cases i <;> first | rfl | exact (zero_div (4800 : ℚ)).symm

/-- Both endpoint functions are compared on every one of the 22 coordinates. -/
theorem inheritedBox4_eq_literal :
    spine3.right (15 : Fin 22) (0 : ℚ) = actualLeafBox4 := by
  apply Box.ext
  · intro i
    fin_cases i <;> first | rfl | exact (zero_div (4800 : ℚ)).symm
  · intro i
    fin_cases i <;> first | rfl | exact (zero_div (4800 : ℚ)).symm

/-- Both endpoint functions are compared on every one of the 22 coordinates. -/
theorem inheritedBox5_eq_literal :
    spine2.right (19 : Fin 22) (0 : ℚ) = actualLeafBox5 := by
  apply Box.ext
  · intro i
    fin_cases i <;> first | rfl | exact (zero_div (4800 : ℚ)).symm
  · intro i
    fin_cases i <;> first | rfl | exact (zero_div (4800 : ℚ)).symm

/-- Both endpoint functions are compared on every one of the 22 coordinates. -/
theorem inheritedBox6_eq_literal :
    spine1.right (20 : Fin 22) (0 : ℚ) = actualLeafBox6 := by
  apply Box.ext
  · intro i
    fin_cases i <;> first | rfl | exact (zero_div (4800 : ℚ)).symm
  · intro i
    fin_cases i <;> first | rfl | exact (zero_div (4800 : ℚ)).symm

/-- Both endpoint functions are compared on every one of the 22 coordinates. -/
theorem inheritedBox7_eq_literal :
    spine0.right (21 : Fin 22) (0 : ℚ) = actualLeafBox7 := by
  apply Box.ext
  · intro i
    fin_cases i <;> first | rfl | exact (zero_div (4800 : ℚ)).symm
  · intro i
    fin_cases i <;> first | rfl | exact (zero_div (4800 : ℚ)).symm

def actualFrontier : List (Box 22) :=
  [actualLeafBox0, actualLeafBox1, actualLeafBox2, actualLeafBox3, actualLeafBox4, actualLeafBox5, actualLeafBox6, actualLeafBox7]

/-- This equality binds the tree traversal to all eight independently supplied boxes. -/
theorem leafBoxes_prefix : leafBoxes root prefixTree = actualFrontier := by
  change [spine7,
    spine6.right (11 : Fin 22) (0 : ℚ),
    spine5.right (14 : Fin 22) (0 : ℚ),
    spine4.right (13 : Fin 22) (0 : ℚ),
    spine3.right (15 : Fin 22) (0 : ℚ),
    spine2.right (19 : Fin 22) (0 : ℚ),
    spine1.right (20 : Fin 22) (0 : ℚ),
    spine0.right (21 : Fin 22) (0 : ℚ)] = [actualLeafBox0, actualLeafBox1, actualLeafBox2, actualLeafBox3, actualLeafBox4, actualLeafBox5, actualLeafBox6, actualLeafBox7]
  rw [inheritedBox0_eq_literal, inheritedBox1_eq_literal, inheritedBox2_eq_literal, inheritedBox3_eq_literal, inheritedBox4_eq_literal, inheritedBox5_eq_literal, inheritedBox6_eq_literal, inheritedBox7_eq_literal]

theorem actualFrontier_length : actualFrontier.length = 8 := by
  rfl

/-- Complete prefix coverage retains the first terminal record and all seven siblings. -/
theorem prefix_cover :
    ∀ x ∈ root.denote, ∃ b ∈ actualFrontier, x ∈ b.denote := by
  simpa only [leafBoxes_prefix] using cover_all_leaves root prefixTree

/-- The eight closed boxes have exactly the root as their union. -/
theorem root_mem_iff_actualFrontier (x : Fin 22 → ℝ) :
    x ∈ root.denote ↔ ∃ b ∈ actualFrontier, x ∈ b.denote := by
  simpa only [leafBoxes_prefix] using
    mem_root_iff_mem_leaf root prefixTree prefix_wellFormed x

/-- Safety remains conditional on EVERY leaf, including the first C-record box.
No leaf checker result is imported through the parser or through a Boolean flag. -/
theorem root_safe_if_all_frontier (P : (Fin 22 → ℝ) → Prop)
    (h : ∀ b ∈ actualFrontier, ∀ x ∈ b.denote, P x) :
    ∀ x ∈ root.denote, P x := by
  apply safe_of_all_leaves root prefixTree P
  simpa only [leafBoxes_prefix] using h

end Rho5.Shared.MainlineTreeCover.V31Prefix
