import Rho5.Shared.CertificateContraction.QuadraticLift
import Rho5.Shared.MainlineTreeCover.Box

/-!
# The actual V31 model encoded in C03 quadratic syntax

Generated by m02/tools/generate_model.py from the frozen mc_exact_model.json.
JSON SHA256: 5fb91ced098b36174e1f307f543cf30872a075f262d477bc2bdb378b39aa94c5
Original dimensions: 22 coordinates, 35 ordered shared products, 106 rows.
The JSON basis satisfies sum(coeff[j] * lifted[j]) <= rhs, with the
positive base multiplier 1600.  integerPolynomials stores rhs - sum(coeff*z)
EXACTLY; polynomials divides every sparse coefficient by 1600 to recover the
original polynomial.  SameSource uses those original polynomials, while
generatedSystem consumes integerPolynomials through the proved positive-scale
equivalence.  Its first 106 rows therefore retain the JSON integer basis and
rhs; its 140 added McCormick rows have no extra 1600 multiplier.

No generated-row statement is assumed by SameSource.  Every dynamic row and
every lifted-box bound comes from the already proved C03 quadratic_lift_source.
The original matrix-to-these-polynomials bridge remains a separate task.
The JSON parser and source-byte hash are external provenance, not Lean theorems.
This generated source still requires the owning mainline's compilation/audit.
-/

namespace Rho5.Shared.MainlineTreeCover.V31Batch.Model

open Rho5.Shared.CertificateContraction (ProductPairs QAtom QPolynomial)

def baseMultiplier : ℚ := 1600

def variableNames : List String := ["k", "r", "w", "A", "B", "c", "d", "p", "e", "be", "u0", "u1", "u2", "x0", "x1", "x2", "v0", "v1", "v2", "q0", "q1", "q2"]

def rowNames : List String := ["e+", "e-", "beta+", "beta-", "head+", "head-", "u0+", "u0-", "x0+", "x0-", "v0+", "v0-", "q0+", "q0-", "L0+", "L0-", "P0+", "P0-", "D00-", "S00+", "S00-", "O00+", "O00-", "D01+", "D01-", "S01+", "S01-", "O01+", "O01-", "D02+", "D02-", "S02+", "S02-", "O02+", "O02-", "u1+", "u1-", "x1+", "x1-", "v1+", "v1-", "q1+", "q1-", "L1+", "L1-", "P1+", "P1-", "D10+", "D10-", "S10+", "S10-", "O10+", "O10-", "D11+", "D11-", "S11+", "S11-", "O11+", "O11-", "D12+", "D12-", "S12+", "S12-", "O12+", "O12-", "u2+", "u2-", "x2+", "x2-", "v2+", "v2-", "q2+", "q2-", "L2+", "L2-", "P2+", "P2-", "D20+", "D20-", "S20+", "S20-", "O20+", "O20-", "D21+", "D21-", "S21+", "S21-", "O21+", "O21-", "D22+", "D22-", "S22+", "S22-", "O22+", "O22-", "F", "Fcore", "r+w", "det3", "plower", "rAd", "rBc", "rAc", "B-A", "B", "cd"]

theorem variableNames_length : variableNames.length = 22 := by decide
theorem rowNames_length : rowNames.length = 106 := by decide

/-- Each actual index is constructed with its own bound proof, never wrapped. -/
def actualPairs : ProductPairs 22 35 := fun q =>
  match q.val with
  | 0 => (⟨15, by decide⟩, ⟨21, by decide⟩)
  | 1 => (⟨15, by decide⟩, ⟨20, by decide⟩)
  | 2 => (⟨15, by decide⟩, ⟨19, by decide⟩)
  | 3 => (⟨14, by decide⟩, ⟨21, by decide⟩)
  | 4 => (⟨14, by decide⟩, ⟨20, by decide⟩)
  | 5 => (⟨14, by decide⟩, ⟨19, by decide⟩)
  | 6 => (⟨13, by decide⟩, ⟨21, by decide⟩)
  | 7 => (⟨13, by decide⟩, ⟨20, by decide⟩)
  | 8 => (⟨13, by decide⟩, ⟨19, by decide⟩)
  | 9 => (⟨12, by decide⟩, ⟨18, by decide⟩)
  | 10 => (⟨12, by decide⟩, ⟨17, by decide⟩)
  | 11 => (⟨12, by decide⟩, ⟨16, by decide⟩)
  | 12 => (⟨11, by decide⟩, ⟨18, by decide⟩)
  | 13 => (⟨11, by decide⟩, ⟨17, by decide⟩)
  | 14 => (⟨11, by decide⟩, ⟨16, by decide⟩)
  | 15 => (⟨10, by decide⟩, ⟨18, by decide⟩)
  | 16 => (⟨10, by decide⟩, ⟨17, by decide⟩)
  | 17 => (⟨10, by decide⟩, ⟨16, by decide⟩)
  | 18 => (⟨9, by decide⟩, ⟨18, by decide⟩)
  | 19 => (⟨9, by decide⟩, ⟨17, by decide⟩)
  | 20 => (⟨9, by decide⟩, ⟨16, by decide⟩)
  | 21 => (⟨8, by decide⟩, ⟨12, by decide⟩)
  | 22 => (⟨8, by decide⟩, ⟨11, by decide⟩)
  | 23 => (⟨8, by decide⟩, ⟨10, by decide⟩)
  | 24 => (⟨8, by decide⟩, ⟨9, by decide⟩)
  | 25 => (⟨7, by decide⟩, ⟨15, by decide⟩)
  | 26 => (⟨7, by decide⟩, ⟨14, by decide⟩)
  | 27 => (⟨7, by decide⟩, ⟨13, by decide⟩)
  | 28 => (⟨4, by decide⟩, ⟨6, by decide⟩)
  | 29 => (⟨4, by decide⟩, ⟨5, by decide⟩)
  | 30 => (⟨3, by decide⟩, ⟨6, by decide⟩)
  | 31 => (⟨3, by decide⟩, ⟨5, by decide⟩)
  | 32 => (⟨0, by decide⟩, ⟨7, by decide⟩)
  | 33 => (⟨0, by decide⟩, ⟨6, by decide⟩)
  | 34 => (⟨0, by decide⟩, ⟨5, by decide⟩)
  | _ => (⟨0, by decide⟩, ⟨0, by decide⟩)

/-- The finite indexed table has exactly the ordered JSON pair values. -/
theorem actualPairs_values :
    List.ofFn (fun q : Fin 35 => ((actualPairs q).1.val, (actualPairs q).2.val)) =
      [(15, 21), (15, 20), (15, 19), (14, 21), (14, 20), (14, 19), (13, 21), (13, 20), (13, 19), (12, 18), (12, 17), (12, 16), (11, 18), (11, 17), (11, 16), (10, 18), (10, 17), (10, 16), (9, 18), (9, 17), (9, 16), (8, 12), (8, 11), (8, 10), (8, 9), (7, 15), (7, 14), (7, 13), (4, 6), (4, 5), (3, 6), (3, 5), (0, 7), (0, 6), (0, 5)] := by decide

/-- Actual integer basis: constant rhs and NEGATED left-hand coefficients.
Zero coefficients are omitted; nonzero columns remain in ascending order. -/
def integerPolynomials : Fin 106 → QPolynomial 22 35 := fun r =>
  match r.val with
  | 0 => [(1600, .constant), (-1600, .linear ⟨8, by decide⟩)]
  | 1 => [(1600, .constant), (1600, .linear ⟨8, by decide⟩)]
  | 2 => [(1600, .constant), (-1600, .linear ⟨9, by decide⟩)]
  | 3 => [(1600, .constant), (1600, .linear ⟨9, by decide⟩)]
  | 4 => [(1600, .constant), (-1600, .linear ⟨7, by decide⟩), (1600, .product ⟨24, by decide⟩)]
  | 5 => [(1600, .constant), (1600, .linear ⟨7, by decide⟩), (-1600, .product ⟨24, by decide⟩)]
  | 6 => [(1600, .constant), (-1600, .linear ⟨10, by decide⟩)]
  | 7 => [(1600, .constant), (1600, .linear ⟨10, by decide⟩)]
  | 8 => [(1600, .constant), (-1600, .linear ⟨13, by decide⟩)]
  | 9 => [(1600, .constant), (1600, .linear ⟨13, by decide⟩)]
  | 10 => [(1600, .constant), (-1600, .linear ⟨16, by decide⟩)]
  | 11 => [(1600, .constant), (1600, .linear ⟨16, by decide⟩)]
  | 12 => [(1600, .linear ⟨7, by decide⟩), (-1600, .linear ⟨19, by decide⟩)]
  | 13 => [(1600, .linear ⟨7, by decide⟩), (1600, .linear ⟨19, by decide⟩)]
  | 14 => [(1600, .constant), (1600, .product ⟨23, by decide⟩), (-1600, .product ⟨27, by decide⟩)]
  | 15 => [(1600, .constant), (-1600, .product ⟨23, by decide⟩), (1600, .product ⟨27, by decide⟩)]
  | 16 => [(1600, .constant), (-1600, .linear ⟨19, by decide⟩), (-1600, .product ⟨20, by decide⟩)]
  | 17 => [(1600, .constant), (1600, .linear ⟨19, by decide⟩), (1600, .product ⟨20, by decide⟩)]
  | 18 => [(3200, .linear ⟨0, by decide⟩)]
  | 19 => [(-1600, .linear ⟨0, by decide⟩), (1600, .linear ⟨7, by decide⟩), (-1600, .product ⟨8, by decide⟩)]
  | 20 => [(1600, .linear ⟨0, by decide⟩), (1600, .linear ⟨7, by decide⟩), (1600, .product ⟨8, by decide⟩)]
  | 21 => [(1600, .constant), (-1600, .linear ⟨0, by decide⟩), (-1600, .product ⟨8, by decide⟩), (-1600, .product ⟨17, by decide⟩)]
  | 22 => [(1600, .constant), (1600, .linear ⟨0, by decide⟩), (1600, .product ⟨8, by decide⟩), (1600, .product ⟨17, by decide⟩)]
  | 23 => [(1600, .linear ⟨0, by decide⟩), (-1600, .linear ⟨3, by decide⟩)]
  | 24 => [(1600, .linear ⟨0, by decide⟩), (1600, .linear ⟨3, by decide⟩)]
  | 25 => [(-1600, .linear ⟨3, by decide⟩), (1600, .linear ⟨7, by decide⟩), (-1600, .product ⟨7, by decide⟩)]
  | 26 => [(1600, .linear ⟨3, by decide⟩), (1600, .linear ⟨7, by decide⟩), (1600, .product ⟨7, by decide⟩)]
  | 27 => [(1600, .constant), (-1600, .linear ⟨3, by decide⟩), (-1600, .product ⟨7, by decide⟩), (-1600, .product ⟨16, by decide⟩)]
  | 28 => [(1600, .constant), (1600, .linear ⟨3, by decide⟩), (1600, .product ⟨7, by decide⟩), (1600, .product ⟨16, by decide⟩)]
  | 29 => [(1600, .linear ⟨0, by decide⟩), (-1600, .linear ⟨4, by decide⟩)]
  | 30 => [(1600, .linear ⟨0, by decide⟩), (1600, .linear ⟨4, by decide⟩)]
  | 31 => [(-1600, .linear ⟨4, by decide⟩), (1600, .linear ⟨7, by decide⟩), (-1600, .product ⟨6, by decide⟩)]
  | 32 => [(1600, .linear ⟨4, by decide⟩), (1600, .linear ⟨7, by decide⟩), (1600, .product ⟨6, by decide⟩)]
  | 33 => [(1600, .constant), (-1600, .linear ⟨4, by decide⟩), (-1600, .product ⟨6, by decide⟩), (-1600, .product ⟨15, by decide⟩)]
  | 34 => [(1600, .constant), (1600, .linear ⟨4, by decide⟩), (1600, .product ⟨6, by decide⟩), (1600, .product ⟨15, by decide⟩)]
  | 35 => [(1600, .constant), (-1600, .linear ⟨11, by decide⟩)]
  | 36 => [(1600, .constant), (1600, .linear ⟨11, by decide⟩)]
  | 37 => [(1600, .constant), (-1600, .linear ⟨14, by decide⟩)]
  | 38 => [(1600, .constant), (1600, .linear ⟨14, by decide⟩)]
  | 39 => [(1600, .constant), (-1600, .linear ⟨17, by decide⟩)]
  | 40 => [(1600, .constant), (1600, .linear ⟨17, by decide⟩)]
  | 41 => [(1600, .linear ⟨7, by decide⟩), (-1600, .linear ⟨20, by decide⟩)]
  | 42 => [(1600, .linear ⟨7, by decide⟩), (1600, .linear ⟨20, by decide⟩)]
  | 43 => [(1600, .constant), (1600, .product ⟨22, by decide⟩), (-1600, .product ⟨26, by decide⟩)]
  | 44 => [(1600, .constant), (-1600, .product ⟨22, by decide⟩), (1600, .product ⟨26, by decide⟩)]
  | 45 => [(1600, .constant), (-1600, .linear ⟨20, by decide⟩), (-1600, .product ⟨19, by decide⟩)]
  | 46 => [(1600, .constant), (1600, .linear ⟨20, by decide⟩), (1600, .product ⟨19, by decide⟩)]
  | 47 => [(1600, .linear ⟨0, by decide⟩), (-1600, .product ⟨34, by decide⟩)]
  | 48 => [(1600, .linear ⟨0, by decide⟩), (1600, .product ⟨34, by decide⟩)]
  | 49 => [(1600, .linear ⟨7, by decide⟩), (-1600, .product ⟨5, by decide⟩), (-1600, .product ⟨34, by decide⟩)]
  | 50 => [(1600, .linear ⟨7, by decide⟩), (1600, .product ⟨5, by decide⟩), (1600, .product ⟨34, by decide⟩)]
  | 51 => [(1600, .constant), (-1600, .product ⟨5, by decide⟩), (-1600, .product ⟨14, by decide⟩), (-1600, .product ⟨34, by decide⟩)]
  | 52 => [(1600, .constant), (1600, .product ⟨5, by decide⟩), (1600, .product ⟨14, by decide⟩), (1600, .product ⟨34, by decide⟩)]
  | 53 => [(1600, .linear ⟨0, by decide⟩), (-1600, .linear ⟨1, by decide⟩), (-1600, .product ⟨31, by decide⟩)]
  | 54 => [(1600, .linear ⟨0, by decide⟩), (1600, .linear ⟨1, by decide⟩), (1600, .product ⟨31, by decide⟩)]
  | 55 => [(-1600, .linear ⟨1, by decide⟩), (1600, .linear ⟨7, by decide⟩), (-1600, .product ⟨4, by decide⟩), (-1600, .product ⟨31, by decide⟩)]
  | 56 => [(1600, .linear ⟨1, by decide⟩), (1600, .linear ⟨7, by decide⟩), (1600, .product ⟨4, by decide⟩), (1600, .product ⟨31, by decide⟩)]
  | 57 => [(1600, .constant), (-1600, .linear ⟨1, by decide⟩), (-1600, .product ⟨4, by decide⟩), (-1600, .product ⟨13, by decide⟩), (-1600, .product ⟨31, by decide⟩)]
  | 58 => [(1600, .constant), (1600, .linear ⟨1, by decide⟩), (1600, .product ⟨4, by decide⟩), (1600, .product ⟨13, by decide⟩), (1600, .product ⟨31, by decide⟩)]
  | 59 => [(1600, .linear ⟨0, by decide⟩), (-1600, .linear ⟨1, by decide⟩), (-1600, .product ⟨29, by decide⟩)]
  | 60 => [(1600, .linear ⟨0, by decide⟩), (1600, .linear ⟨1, by decide⟩), (1600, .product ⟨29, by decide⟩)]
  | 61 => [(-1600, .linear ⟨1, by decide⟩), (1600, .linear ⟨7, by decide⟩), (-1600, .product ⟨3, by decide⟩), (-1600, .product ⟨29, by decide⟩)]
  | 62 => [(1600, .linear ⟨1, by decide⟩), (1600, .linear ⟨7, by decide⟩), (1600, .product ⟨3, by decide⟩), (1600, .product ⟨29, by decide⟩)]
  | 63 => [(1600, .constant), (-1600, .linear ⟨1, by decide⟩), (-1600, .product ⟨3, by decide⟩), (-1600, .product ⟨12, by decide⟩), (-1600, .product ⟨29, by decide⟩)]
  | 64 => [(1600, .constant), (1600, .linear ⟨1, by decide⟩), (1600, .product ⟨3, by decide⟩), (1600, .product ⟨12, by decide⟩), (1600, .product ⟨29, by decide⟩)]
  | 65 => [(1600, .constant), (-1600, .linear ⟨12, by decide⟩)]
  | 66 => [(1600, .constant), (1600, .linear ⟨12, by decide⟩)]
  | 67 => [(1600, .constant), (-1600, .linear ⟨15, by decide⟩)]
  | 68 => [(1600, .constant), (1600, .linear ⟨15, by decide⟩)]
  | 69 => [(1600, .constant), (-1600, .linear ⟨18, by decide⟩)]
  | 70 => [(1600, .constant), (1600, .linear ⟨18, by decide⟩)]
  | 71 => [(1600, .linear ⟨7, by decide⟩), (-1600, .linear ⟨21, by decide⟩)]
  | 72 => [(1600, .linear ⟨7, by decide⟩), (1600, .linear ⟨21, by decide⟩)]
  | 73 => [(1600, .constant), (1600, .product ⟨21, by decide⟩), (-1600, .product ⟨25, by decide⟩)]
  | 74 => [(1600, .constant), (-1600, .product ⟨21, by decide⟩), (1600, .product ⟨25, by decide⟩)]
  | 75 => [(1600, .constant), (-1600, .linear ⟨21, by decide⟩), (-1600, .product ⟨18, by decide⟩)]
  | 76 => [(1600, .constant), (1600, .linear ⟨21, by decide⟩), (1600, .product ⟨18, by decide⟩)]
  | 77 => [(1600, .linear ⟨0, by decide⟩), (-1600, .product ⟨33, by decide⟩)]
  | 78 => [(1600, .linear ⟨0, by decide⟩), (1600, .product ⟨33, by decide⟩)]
  | 79 => [(1600, .linear ⟨7, by decide⟩), (-1600, .product ⟨2, by decide⟩), (-1600, .product ⟨33, by decide⟩)]
  | 80 => [(1600, .linear ⟨7, by decide⟩), (1600, .product ⟨2, by decide⟩), (1600, .product ⟨33, by decide⟩)]
  | 81 => [(1600, .constant), (-1600, .product ⟨2, by decide⟩), (-1600, .product ⟨11, by decide⟩), (-1600, .product ⟨33, by decide⟩)]
  | 82 => [(1600, .constant), (1600, .product ⟨2, by decide⟩), (1600, .product ⟨11, by decide⟩), (1600, .product ⟨33, by decide⟩)]
  | 83 => [(1600, .linear ⟨0, by decide⟩), (-1600, .linear ⟨1, by decide⟩), (-1600, .product ⟨30, by decide⟩)]
  | 84 => [(1600, .linear ⟨0, by decide⟩), (1600, .linear ⟨1, by decide⟩), (1600, .product ⟨30, by decide⟩)]
  | 85 => [(-1600, .linear ⟨1, by decide⟩), (1600, .linear ⟨7, by decide⟩), (-1600, .product ⟨1, by decide⟩), (-1600, .product ⟨30, by decide⟩)]
  | 86 => [(1600, .linear ⟨1, by decide⟩), (1600, .linear ⟨7, by decide⟩), (1600, .product ⟨1, by decide⟩), (1600, .product ⟨30, by decide⟩)]
  | 87 => [(1600, .constant), (-1600, .linear ⟨1, by decide⟩), (-1600, .product ⟨1, by decide⟩), (-1600, .product ⟨10, by decide⟩), (-1600, .product ⟨30, by decide⟩)]
  | 88 => [(1600, .constant), (1600, .linear ⟨1, by decide⟩), (1600, .product ⟨1, by decide⟩), (1600, .product ⟨10, by decide⟩), (1600, .product ⟨30, by decide⟩)]
  | 89 => [(1600, .linear ⟨0, by decide⟩), (-1600, .linear ⟨2, by decide⟩), (-1600, .product ⟨28, by decide⟩)]
  | 90 => [(1600, .linear ⟨0, by decide⟩), (1600, .linear ⟨2, by decide⟩), (1600, .product ⟨28, by decide⟩)]
  | 91 => [(-1600, .linear ⟨2, by decide⟩), (1600, .linear ⟨7, by decide⟩), (-1600, .product ⟨0, by decide⟩), (-1600, .product ⟨28, by decide⟩)]
  | 92 => [(1600, .linear ⟨2, by decide⟩), (1600, .linear ⟨7, by decide⟩), (1600, .product ⟨0, by decide⟩), (1600, .product ⟨28, by decide⟩)]
  | 93 => [(1600, .constant), (-1600, .linear ⟨2, by decide⟩), (-1600, .product ⟨0, by decide⟩), (-1600, .product ⟨9, by decide⟩), (-1600, .product ⟨28, by decide⟩)]
  | 94 => [(1600, .constant), (1600, .linear ⟨2, by decide⟩), (1600, .product ⟨0, by decide⟩), (1600, .product ⟨9, by decide⟩), (1600, .product ⟨28, by decide⟩)]
  | 95 => [(-6612, .constant), (1600, .linear ⟨1, by decide⟩), (-1600, .linear ⟨2, by decide⟩)]
  | 96 => [(3600, .linear ⟨0, by decide⟩), (-1600, .linear ⟨1, by decide⟩), (1600, .linear ⟨2, by decide⟩)]
  | 97 => [(1600, .linear ⟨1, by decide⟩), (1600, .linear ⟨2, by decide⟩)]
  | 98 => [(6400, .constant), (-1600, .product ⟨32, by decide⟩)]
  | 99 => [(-1600, .linear ⟨1, by decide⟩), (1600, .linear ⟨2, by decide⟩), (6400, .linear ⟨7, by decide⟩)]
  | 100 => [(1600, .linear ⟨0, by decide⟩), (-1600, .linear ⟨1, by decide⟩), (1600, .product ⟨33, by decide⟩)]
  | 101 => [(1600, .linear ⟨0, by decide⟩), (-1600, .linear ⟨1, by decide⟩), (-1600, .linear ⟨4, by decide⟩)]
  | 102 => [(1600, .linear ⟨0, by decide⟩), (-1600, .linear ⟨1, by decide⟩), (-1600, .linear ⟨3, by decide⟩)]
  | 103 => [(3200, .linear ⟨0, by decide⟩), (-1600, .linear ⟨1, by decide⟩), (1600, .linear ⟨2, by decide⟩), (-1600, .linear ⟨3, by decide⟩), (1600, .linear ⟨4, by decide⟩)]
  | 104 => [(3200, .linear ⟨0, by decide⟩), (-1600, .linear ⟨1, by decide⟩), (1600, .linear ⟨2, by decide⟩), (-1600, .linear ⟨4, by decide⟩)]
  | 105 => [(-106, .constant), (1600, .linear ⟨5, by decide⟩), (-1600, .linear ⟨6, by decide⟩)]
  | _ => []

/-- The original source polynomials, normalized by the actual positive 1600. -/
def polynomials (r : Fin 106) : QPolynomial 22 35 :=
  (integerPolynomials r).map (fun term => (term.1 / baseMultiplier, term.2))

private theorem eval_div_base (p : QPolynomial 22 35) (x : Fin 22 → ℝ) :
    QPolynomial.eval actualPairs x (p.map (fun term => (term.1 / baseMultiplier, term.2))) =
      p.eval actualPairs x / (1600 : ℝ) := by
  induction p with
  | nil => simp [Rho5.Shared.CertificateContraction.QPolynomial.eval]
  | cons term ps ih =>
      rcases term with ⟨c, a⟩
      simp only [List.map_cons, Rho5.Shared.CertificateContraction.QPolynomial.eval, ih]
      rw [Rat.cast_div]
      norm_num [baseMultiplier]
      ring

/-- This is the explicit positive-scale relation, not a source assumption. -/
theorem polynomial_eval_eq_integer_div (r : Fin 106) (x : Fin 22 → ℝ) :
    (polynomials r).eval actualPairs x =
      (integerPolynomials r).eval actualPairs x / (1600 : ℝ) :=
  eval_div_base (integerPolynomials r) x

/-- Same-source feasibility requires only the ACTUAL original polynomials. -/
def SameSource (x : Fin 22 → ℝ) : Prop :=
  ∀ r : Fin 106, 0 ≤ (polynomials r).eval actualPairs x

def source : Set (Fin 22 → ℝ) := {x | SameSource x}

theorem sameSource_iff_integer (x : Fin 22 → ℝ) :
    SameSource x ↔ ∀ r : Fin 106, 0 ≤ (integerPolynomials r).eval actualPairs x := by
  constructor
  · intro h r
    have hr := h r
    rw [polynomial_eval_eq_integer_div] at hr
    linarith
  · intro h r
    rw [polynomial_eval_eq_integer_div]
    exact div_nonneg (h r) (by norm_num)

/-- Reuse C03's box type without changing any endpoint of the current M02 box. -/
def toContractionBox (b : Rho5.Shared.MainlineTreeCover.Box 22) :
    Rho5.Shared.CertificateContraction.Box 22 := ⟨b.lo, b.hi⟩

theorem toContractionBox_contains_iff (b : Rho5.Shared.MainlineTreeCover.Box 22)
    (x : Fin 22 → ℝ) :
    (toContractionBox b).Contains x ↔ x ∈ b.denote := Iff.rfl

def liftedPoint (x : Fin 22 → ℝ) : Fin 57 → ℝ :=
  Rho5.Shared.CertificateContraction.liftPoint actualPairs x

def liftedBox (b : Rho5.Shared.MainlineTreeCover.Box 22) :
    Rho5.Shared.CertificateContraction.Box 57 :=
  Rho5.Shared.CertificateContraction.liftBox actualPairs (toContractionBox b)

/-- The actual 106 INTEGER-basis rows, followed by 35*4 unscaled McCormick
rows generated from THIS box.  This matches TerminalData's row scales. -/
def generatedSystem (b : Rho5.Shared.MainlineTreeCover.Box 22) :
    Rho5.Shared.CertificateContraction.Rows 57 246 :=
  Rho5.Shared.CertificateContraction.generatedRows actualPairs integerPolynomials (toContractionBox b)

def generatedRow (b : Rho5.Shared.MainlineTreeCover.Box 22) (i : Fin 246) :
    Rho5.Shared.CertificateContraction.SparseRow 57 :=
  Rho5.Shared.CertificateContraction.generatedRow actualPairs integerPolynomials (toContractionBox b) i

/-- The lift-box enclosure itself needs no source-polynomial premise. -/
theorem liftedBox_contains (b : Rho5.Shared.MainlineTreeCover.Box 22)
    (x : Fin 22 → ℝ) (hb : x ∈ b.denote) :
    (liftedBox b).Contains (liftedPoint x) :=
  Rho5.Shared.CertificateContraction.liftBox_contains actualPairs (toContractionBox b) x hb

/-- Main consumer: original source + this original box imply all 246 generated
rows and all 57 lifted bounds.  The positive 1600 equivalence pays the integer
polynomial premises; no generated row is passed as a hypothesis. -/
theorem model_source_on_box (b : Rho5.Shared.MainlineTreeCover.Box 22)
    (x : Fin 22 → ℝ) (hb : x ∈ b.denote) (hx : SameSource x) :
    (liftedBox b).Contains (liftedPoint x) ∧
      (generatedSystem b).Holds (liftedPoint x) :=
  Rho5.Shared.CertificateContraction.quadratic_lift_source
    actualPairs integerPolynomials (toContractionBox b) x hb
    ((sameSource_iff_integer x).mp hx)

theorem generatedSystem_holds (b : Rho5.Shared.MainlineTreeCover.Box 22)
    (x : Fin 22 → ℝ) (hb : x ∈ b.denote) (hx : SameSource x) :
    (generatedSystem b).Holds (liftedPoint x) :=
  (model_source_on_box b x hb hx).2

theorem project_liftedPoint (x : Fin 22 → ℝ) :
    Rho5.Shared.CertificateContraction.projectPoint (n := 22) (k := 35) (liftedPoint x) = x :=
  Rho5.Shared.CertificateContraction.project_lift actualPairs x

end Rho5.Shared.MainlineTreeCover.V31Batch.Model
