/-
D13 — the complete legal elimination trace: the inductive relation
==================================================================

`LegalTrace A values` is the *actual* relation generated by the frozen one-step
update of D10: `values` is the list of the successive pivot absolute values that a
legal complete-pivot elimination produces, starting from `A`.

The three constructors are exactly the three ways a run can be in:

* `empty`    — the `0 × 0` matrix has the empty trace `[]` (no extra `0` is added
               at the terminal stage);
* `zeroStop` — a positive-order **zero** matrix has the trace `[0]` and stops
               immediately (there is no legal non-zero pivot to continue with);
* `step`     — a positive-order matrix with a chosen position `(p, q)` that carries
               the frozen `Rho5.Pivot.IsCompletePivot A p q` **and** `A p q ≠ 0`,
               whose tail is a trace of the frozen one-step update
               `Rho5.PivotReindex.pivotSchur A p q`; the trace then starts with the
               actual pivot absolute value `|A p q|`.

There is no constructor that accepts an arbitrary certificate, no constructor that
assumes a target bound, and no constructor placing an arbitrary list into the
relation: every list entry is paid for by a legal, non-zero complete pivot.
Tied complete pivots are all legal (the frozen predicate is used unchanged), so a
matrix may have several different traces; nothing here requires a unique choice.

Scope (frozen by the D13 card): this module supplies the relation and its
structural/scaling properties.  It does **not** prove that every matrix has a
trace — that existence statement is the next dependency (D12's stagewise pivot
existence) and is deliberately absent here.
-/
import Rho5.Shared.Conventions
import Rho5.Shared.Pivot
import Rho5.Shared.PivotReindex

namespace Rho5.CompletePivotPath

open Rho5

/-- **The legal elimination trace relation.**  `n` is the (implicit) order of the
matrix and is an index, so the two positive-order constructors can talk about the
`(n+1) × (n+1)` case while the recursive occurrence is the `n × n` update. -/
inductive LegalTrace : {n : ℕ} → Matrix (Fin n) (Fin n) ℝ → List ℝ → Prop where
  /-- The `0 × 0` matrix: the trace is the empty list. -/
  | empty : LegalTrace (0 : Matrix (Fin 0) (Fin 0) ℝ) []
  /-- A positive-order zero matrix stops immediately with the single value `0`. -/
  | zeroStop {n : ℕ} {A : Matrix (Fin (n + 1)) (Fin (n + 1)) ℝ} (hzero : A = 0) :
      LegalTrace A [0]
  /-- One legal elimination step: a complete pivot that is actually non-zero, with
  the frozen Schur update of D10 as the remaining matrix. -/
  | step {n : ℕ} {A : Matrix (Fin (n + 1)) (Fin (n + 1)) ℝ} (p q : Fin (n + 1))
      (hmax : Rho5.Pivot.IsCompletePivot A p q) (hne : A p q ≠ 0) {tail : List ℝ}
      (htail : LegalTrace (Rho5.PivotReindex.pivotSchur A p q) tail) :
      LegalTrace A (|A p q| :: tail)

/-! ## Structural properties -/

/-- **Goal 1 (length).** A trace of an `n × n` matrix has at most `n` entries: the
order drops by exactly one at every `step`. -/
theorem length_le {n : ℕ} {A : Matrix (Fin n) (Fin n) ℝ} {values : List ℝ}
    (h : LegalTrace A values) : values.length ≤ n := by
  induction h with
  | empty => simp
  | zeroStop hzero => simp
  | step p q hmax hne htail ih => simpa using Nat.succ_le_succ ih

/-- **Goal 1 (nonnegativity).** Every recorded value is an absolute value, hence
nonnegative. -/
theorem nonneg {n : ℕ} {A : Matrix (Fin n) (Fin n) ℝ} {values : List ℝ}
    (h : LegalTrace A values) : ∀ v ∈ values, 0 ≤ v := by
  induction h with
  | empty => simp
  | zeroStop hzero => intro v hv; rw [List.mem_singleton] at hv; rw [hv]
  | step p q hmax hne htail ih =>
      intro v hv
      rcases List.mem_cons.mp hv with rfl | hv'
      · exact abs_nonneg _
      · exact ih v hv'

/-- **Goal 1 (nonempty).** A positive-order trace is never the empty list: the
`0 × 0` terminal is the only source of `[]`. -/
theorem ne_nil_of_pos {n : ℕ} {A : Matrix (Fin (n + 1)) (Fin (n + 1)) ℝ} {values : List ℝ}
    (h : LegalTrace A values) : values ≠ [] := by
  cases h with
  | zeroStop hzero => simp
  | step p q hmax hne htail => simp

/-- **Goal 1 (characterisation of the empty trace).** The empty list occurs exactly
for order `0`; the terminal stage adds no extra `0`. -/
theorem eq_nil_iff {n : ℕ} {A : Matrix (Fin n) (Fin n) ℝ} :
    LegalTrace A ([] : List ℝ) ↔ n = 0 := by
  constructor
  · intro h
    cases h with
    | empty => rfl
  · intro hn
    subst hn
    have hA : A = 0 := by
      funext i j
      exact Fin.elim0 i
    rw [hA]
    exact LegalTrace.empty

/-- **Goal 1 (decomposition at a non-zero matrix).** Every trace of a *nonzero*
positive-order matrix really does start with a genuine legal step: there are actual
indices `(p, q)` carrying `IsCompletePivot A p q` and `A p q ≠ 0`, and the tail is a
trace of the frozen D10 Schur update.  This is the decomposition later
existence/bound arguments consume. -/
theorem exists_step_of_ne_zero {n : ℕ} {A : Matrix (Fin (n + 1)) (Fin (n + 1)) ℝ}
    (hA : A ≠ 0) {values : List ℝ} (h : LegalTrace A values) :
    ∃ (p q : Fin (n + 1)) (tail : List ℝ),
      Rho5.Pivot.IsCompletePivot A p q ∧ A p q ≠ 0 ∧
        values = |A p q| :: tail ∧ LegalTrace (Rho5.PivotReindex.pivotSchur A p q) tail := by
  cases h with
  | zeroStop hzero => exact absurd hzero hA
  | step p q hmax hne htail => exact ⟨p, q, _, hmax, hne, rfl, htail⟩

/-- **Goal 1 (zero matrix).** At a positive-order zero matrix the only possible
trace is `[0]`: `zeroStop` is the sole constructor available, because `step` would
need a non-zero pivot. -/
theorem zero_iff {n : ℕ} {values : List ℝ} :
    LegalTrace (0 : Matrix (Fin (n + 1)) (Fin (n + 1)) ℝ) values ↔ values = [0] := by
  constructor
  · intro h
    cases h with
    | zeroStop hzero => rfl
    | step p q hmax hne htail => exact absurd (Matrix.zero_apply p q) hne
  · intro hv
    rw [hv]
    exact LegalTrace.zeroStop rfl

/-- The tail of a positive-order trace has at most `n` entries (the order really
decreases at every step). -/
theorem tail_length_le {n : ℕ} {A : Matrix (Fin (n + 1)) (Fin (n + 1)) ℝ} {v : ℝ}
    {tail : List ℝ} (h : LegalTrace A (v :: tail)) : tail.length ≤ n := by
  cases h with
  | zeroStop hzero => simp
  | step p q hmax hne htail => simpa using length_le htail

end Rho5.CompletePivotPath
