/-
D34 — coefficient bridge: D05's `pc_i` and D07's `pc_i` agree at the point.

GENERATED by `parallel/D34/scripts/gen_coeff_bridge.py` from the audited
certificate; the index list comes from the certificate, not from hand
transcription.  Each proof unfolds the two definitions and discharges a
one-variable polynomial identity over `ℝ` with `ring`.
-/
import Rho5.Algebraic.CriticalBridge
import Rho5.Algebraic.ScalarAlphaBridge.Bridge

noncomputable section

namespace Rho5.Algebraic.ScalarCandidateAlpha

open Rho5.Algebraic

set_option maxHeartbeats 0

/-- `ev` on a variable is the point's coordinate (`eval` is `eval₂Hom` at
`RingHom.id`; this exposes the library lemma for the D05 abbreviation). -/
theorem ev_X (v : Point) (i : Fin 4) : ev v (MvPolynomial.X i) = v i :=
  MvPolynomial.eval₂Hom_X' (RingHom.id ℝ) v i

/-- The same for the coordinate `g` used by every coefficient. -/
theorem ev_gVar (v : Point) : ev v gVar = v 3 := by
  rw [gVar, ev_X]

/-- The D05 `z`-coefficient list. -/
def pcAt (i : Fin 11) : Poly :=
  ![pc0, pc1, pc2, pc3, pc4, pc5, pc6, pc7, pc8, pc9, pc10] i

/-- The D07 `z`-coefficient list, evaluated at `g`. -/
def bezoutPcAt (g : ℝ) (i : Fin 11) : ℝ :=
  ![BezoutChecks.pc0 g, BezoutChecks.pc1 g, BezoutChecks.pc2 g,
    BezoutChecks.pc3 g, BezoutChecks.pc4 g, BezoutChecks.pc5 g,
    BezoutChecks.pc6 g, BezoutChecks.pc7 g, BezoutChecks.pc8 g,
    BezoutChecks.pc9 g, BezoutChecks.pc10 g] i

theorem eval_pc0 (x y z g : ℝ) :
    ev (point x y z g) pc0 = BezoutChecks.pc0 g := by
  simp only [pc0, BezoutChecks.pc0, gVar, ev_X, map_mul, map_pow,
    map_add, map_ofNat, map_sub, map_neg]
  simp [point, Matrix.cons_val]
  ring

theorem eval_pc1 (x y z g : ℝ) :
    ev (point x y z g) pc1 = BezoutChecks.pc1 g := by
  simp only [pc1, BezoutChecks.pc1, gVar, ev_X, map_mul, map_pow,
    map_add, map_ofNat, map_sub, map_neg]
  simp [point, Matrix.cons_val]
  ring

theorem eval_pc2 (x y z g : ℝ) :
    ev (point x y z g) pc2 = BezoutChecks.pc2 g := by
  simp only [pc2, BezoutChecks.pc2, gVar, ev_X, map_mul, map_pow,
    map_add, map_ofNat, map_sub, map_neg]
  simp [point, Matrix.cons_val]
  ring

theorem eval_pc3 (x y z g : ℝ) :
    ev (point x y z g) pc3 = BezoutChecks.pc3 g := by
  simp only [pc3, BezoutChecks.pc3, gVar, ev_X, map_mul, map_pow,
    map_add, map_ofNat, map_sub, map_neg]
  simp [point, Matrix.cons_val]
  ring

theorem eval_pc4 (x y z g : ℝ) :
    ev (point x y z g) pc4 = BezoutChecks.pc4 g := by
  simp only [pc4, BezoutChecks.pc4, gVar, ev_X, map_mul, map_pow,
    map_add, map_ofNat, map_sub, map_neg]
  simp [point, Matrix.cons_val]
  ring

theorem eval_pc5 (x y z g : ℝ) :
    ev (point x y z g) pc5 = BezoutChecks.pc5 g := by
  simp only [pc5, BezoutChecks.pc5, gVar, ev_X, map_mul, map_pow,
    map_add, map_ofNat, map_sub, map_neg]
  simp [point, Matrix.cons_val]
  ring

theorem eval_pc6 (x y z g : ℝ) :
    ev (point x y z g) pc6 = BezoutChecks.pc6 g := by
  simp only [pc6, BezoutChecks.pc6, gVar, ev_X, map_mul, map_pow,
    map_add, map_ofNat, map_sub, map_neg]
  simp [point, Matrix.cons_val]
  ring

theorem eval_pc7 (x y z g : ℝ) :
    ev (point x y z g) pc7 = BezoutChecks.pc7 g := by
  simp only [pc7, BezoutChecks.pc7, gVar, ev_X, map_mul, map_pow,
    map_add, map_ofNat, map_sub, map_neg]
  simp [point, Matrix.cons_val]
  ring

theorem eval_pc8 (x y z g : ℝ) :
    ev (point x y z g) pc8 = BezoutChecks.pc8 g := by
  simp only [pc8, BezoutChecks.pc8, gVar, ev_X, map_mul, map_pow,
    map_add, map_ofNat, map_sub, map_neg]
  simp [point, Matrix.cons_val]
  ring

theorem eval_pc9 (x y z g : ℝ) :
    ev (point x y z g) pc9 = BezoutChecks.pc9 g := by
  simp only [pc9, BezoutChecks.pc9, gVar, ev_X, map_mul, map_pow,
    map_add, map_ofNat, map_sub, map_neg]
  simp [point, Matrix.cons_val]
  ring

theorem eval_pc10 (x y z g : ℝ) :
    ev (point x y z g) pc10 = BezoutChecks.pc10 g := by
  simp only [pc10, BezoutChecks.pc10, gVar, ev_X, map_mul, map_pow,
    map_add, map_ofNat, map_sub, map_neg]
  simp [point, Matrix.cons_val]
  ring

/-- Coefficient agreement, indexed as the two sums index it. -/
theorem eval_pcAt (x y z g : ℝ) (i : Fin 11) :
    ev (point x y z g) (pcAt i) = bezoutPcAt g i := by
  fin_cases i <;>
    simp only [pcAt, bezoutPcAt, Matrix.cons_val_zero, Matrix.cons_val_one,
      Matrix.head_cons, Matrix.cons_val_fin_one] <;>
    first
      | exact eval_pc0 x y z g
      | exact eval_pc1 x y z g
      | exact eval_pc2 x y z g
      | exact eval_pc3 x y z g
      | exact eval_pc4 x y z g
      | exact eval_pc5 x y z g
      | exact eval_pc6 x y z g
      | exact eval_pc7 x y z g
      | exact eval_pc8 x y z g
      | exact eval_pc9 x y z g
      | exact eval_pc10 x y z g

end Rho5.Algebraic.ScalarCandidateAlpha
