"""Bound only individual untrusted LP calls, never the continuous search.

A persistent, single-threaded child executes scipy.optimize.linprog. A hard wall
limit kills only that solver child and returns an unsuccessful proposal. Frozen
callers then use their existing no-proposal/fallback branches; mathematical
verification and the search worker's identity are untouched.

The pickle files are private IPC generated by this process, never user input.
Do not load diagnostic pickle files received from an untrusted source.
"""
from pathlib import Path
from types import SimpleNamespace
import atexit
import hashlib
import json
import math
import os
import pickle
import selectors
import shutil
import signal
import subprocess
import sys
import threading
import time
import traceback
import uuid

SCHEMA = 'RHO5_INDIVIDUAL_LP_PROCESS_GUARD_V1'
THREAD_ENV = ('OPENBLAS_NUM_THREADS', 'OMP_NUM_THREADS', 'MKL_NUM_THREADS',
              'NUMEXPR_NUM_THREADS', 'BLIS_NUM_THREADS', 'VECLIB_MAXIMUM_THREADS',
              'OMP_THREAD_LIMIT', 'HIGHS_THREADS')


class GuardDeadline(Exception):
    pass


def _sha(data):
    return hashlib.sha256(data).hexdigest()


def _atomic_bytes(path, data, durable=False):
    path = Path(path)
    temporary = path.with_name(path.name + '.tmp.' + str(os.getpid()))
    try:
        with temporary.open('wb') as f:
            f.write(data)
            f.flush()
            if durable:
                os.fsync(f.fileno())
        os.replace(temporary, path)
    finally:
        if temporary.exists():
            temporary.unlink()


def _atomic_json(path, value, durable=False):
    _atomic_bytes(path, (json.dumps(value, sort_keys=True, separators=(',', ':')) + '\n').encode(), durable)


def _failed_result(message):
    # scipy is already loaded in a real search worker; the fallback supports
    # standard-library-only IPC control tests without importing scientific code.
    module = sys.modules.get('scipy.optimize')
    factory = module.OptimizeResult if module is not None else SimpleNamespace
    return factory(success=False, status=4, message=message, fun=None, x=None,
                   nit=0, ineqlin=SimpleNamespace(marginals=None),
                   eqlin=SimpleNamespace(marginals=None))


def _child_cpu_seconds(pid):
    if pid is None or not sys.platform.startswith('linux'):
        return None
    try:
        fields = Path('/proc/' + str(pid) + '/stat').read_text().rsplit(')', 1)[1].split()
        return (int(fields[11]) + int(fields[12])) / os.sysconf('SC_CLK_TCK')
    except (OSError, ValueError, IndexError):
        return None


class LPGuard:
    def __init__(self, folder, *, context_provider=None, hard_timeout_seconds=10.0,
                 startup_timeout_seconds=30.0, helper_memory_bytes=1024**3,
                 max_request_bytes=64 * 1024**2, retained_failures=8,
                 _toy_server=False):
        if not math.isfinite(hard_timeout_seconds) or hard_timeout_seconds <= 0:
            raise ValueError('Hard LP timeout must be finite and positive')
        if not math.isfinite(startup_timeout_seconds) or startup_timeout_seconds <= 0:
            raise ValueError('Startup timeout must be finite and positive')
        self.folder = Path(folder).resolve()
        self.folder.mkdir(parents=True, exist_ok=True)
        self.context_provider = context_provider
        self.timeout = float(hard_timeout_seconds)
        self.startup_timeout = float(startup_timeout_seconds)
        self.memory_limit = int(helper_memory_bytes)
        self.max_request_bytes = int(max_request_bytes)
        self.retained_failures = max(0, int(retained_failures))
        self.toy_server = _toy_server
        self.process = None
        self.selector = None
        self.buffer = b''
        self.lock = threading.Lock()
        self.session = str(os.getpid()) + '_' + uuid.uuid4().hex[:12]
        self.sequence = 0
        self.total_solver_cpu_seconds = 0.0
        self.returned_calls = 0
        self.successful_results = 0
        self.timeout_count = 0
        self.failure_count = 0
        self.diagnostic_errors = 0
        self.last_failure = None
        atexit.register(self.close)

    def _event(self, value, active=True, durable=False):
        value = {'schema': SCHEMA, 'epoch': time.time(), 'search_pid': os.getpid(),
                 'search_worker_restarted': False, **value}
        # Diagnostic I/O is not mathematical acceptance and must not turn a
        # recoverable LP failure into a lost search checkpoint.
        try:
            if active:
                _atomic_json(self.folder / 'ACTIVE_CALL.json', value, durable)
            # Keep per-call current state, but do not append every fast LP to
            # an unbounded log. Failures, helper starts, and each 256-call
            # aggregate remain durable diagnostics.
            if value.get('event') in {'SOLVER_READY', 'LP_FAILURE', 'FAILURE_RETENTION_ERROR', 'LP_CALL_SUMMARY'}:
                with (self.folder / 'EVENTS.jsonl').open('a') as stream:
                    stream.write(json.dumps(value, sort_keys=True) + '\n')
                    stream.flush()
                    if durable:
                        os.fsync(stream.fileno())
        except OSError as exc:
            self.diagnostic_errors += 1
            print('LP_GUARD_DIAGNOSTIC_IO_ERROR ' + repr(exc), file=sys.stderr, flush=True)

    def _stop_helper(self):
        p = self.process
        self.process = None
        if self.selector is not None:
            self.selector.close()
            self.selector = None
        self.buffer = b''
        if p is None:
            return
        if p.poll() is None:
            p.terminate()
            try:
                p.wait(timeout=0.5)
            except subprocess.TimeoutExpired:
                p.kill()
                p.wait(timeout=2)
        for stream in (p.stdin, p.stdout):
            if stream is not None:
                stream.close()

    def close(self):
        self._stop_helper()

    def _reply(self, deadline, call_id=None):
        while True:
            while b'\n' in self.buffer:
                line, self.buffer = self.buffer.split(b'\n', 1)
                answer = json.loads(line)
                if call_id is not None and answer.get('call_id') != call_id:
                    raise RuntimeError('Solver response belongs to a different LP call')
                return answer
            left = deadline - time.monotonic()
            if left <= 0:
                raise GuardDeadline('Individual LP hard wall timeout')
            if self.process.poll() is not None:
                raise RuntimeError('Solver child exited: ' + str(self.process.returncode))
            for key, _mask in self.selector.select(min(0.2, left)):
                block = os.read(key.fd, 65536)
                if not block:
                    raise RuntimeError('Solver child closed response stream')
                self.buffer += block
                if len(self.buffer) > 1024 * 1024:
                    raise RuntimeError('Oversized solver control response')

    def _start_helper(self):
        if self.process is not None and self.process.poll() is None:
            return
        self._stop_helper()
        mode = '--toy-server' if self.toy_server else '--server'
        environment = dict(os.environ)
        environment.update({name: '1' for name in THREAD_ENV})
        command = [sys.executable, '-B', str(Path(__file__).resolve()), mode,
                   str(self.folder), str(self.memory_limit), str(self.max_request_bytes)]
        log = (self.folder / 'SOLVER.log').open('ab')
        try:
            self.process = subprocess.Popen(command, stdin=subprocess.PIPE, stdout=subprocess.PIPE,
                                            stderr=log, env=environment, start_new_session=False,
                                            bufsize=0)
        finally:
            log.close()
        os.set_blocking(self.process.stdout.fileno(), False)
        self.selector = selectors.DefaultSelector()
        self.selector.register(self.process.stdout, selectors.EVENT_READ)
        reply = self._reply(time.monotonic() + self.startup_timeout)
        if reply.get('status') != 'READY':
            raise RuntimeError('Solver child initialization failed: ' + str(reply))
        self._event({'event': 'SOLVER_READY', 'helper_pid': self.process.pid}, active=False)

    def _retain_failure(self, call_id, context, reason, helper_pid,
                        request_written=False, request_sha256=None, solver_cpu_seconds=None):
        self.failure_count += 1
        retained = None
        # Retain the first bounded set of diagnostic inputs; later failures keep
        # hashes, stage/context, logs, and the current request without growing an
        # unlimited archive. These are not proof checkpoints.
        saved = self.folder / 'failed_calls'
        saved.mkdir(exist_ok=True)
        existing = sum(1 for _ in saved.glob('*.pkl'))
        if request_written and existing < self.retained_failures and (self.folder / 'request.pkl').exists():
            target = saved / (call_id + '.pkl')
            shutil.copyfile(self.folder / 'request.pkl', target)
            with target.open('rb') as stream:
                os.fsync(stream.fileno())
            retained = str(target.relative_to(self.folder))
        record = {'event': 'LP_FAILURE', 'call_id': call_id, 'reason': reason,
                  'context': context, 'helper_pid': helper_pid,
                  'request_sha256': request_sha256, 'current_request_written': request_written,
                  'solver_cpu_seconds_observed': solver_cpu_seconds,
                  'total_solver_cpu_seconds': self.total_solver_cpu_seconds,
                  'retained_request': retained, 'retained_failure_limit': self.retained_failures,
                  'fallback': 'RETURN_UNSUCCESSFUL_RESULT_TO_UNCHANGED_PROPOSAL_CALLER'}
        self.last_failure = record
        self._event(record, durable=True)

    def linprog(self, *args, **kwargs):
        with self.lock:
            self.sequence += 1
            call_id = self.session + '_' + str(self.sequence).zfill(8)
            context = self.context_provider() if self.context_provider is not None else {}
            request = {'call_id': call_id, 'args': args, 'kwargs': kwargs}
            begin = time.monotonic()
            helper_pid = None
            child_cpu_before = None
            request_written = False
            request_sha = None
            try:
                payload = pickle.dumps(request, protocol=5)
                if len(payload) > self.max_request_bytes:
                    raise ValueError('LP input exceeds bounded IPC payload size')
                _atomic_bytes(self.folder / 'request.pkl', payload)
                request_written = True
                request_sha = _sha(payload)
                options = kwargs.get('options') or {}
                meta = {'event': 'LP_BEGIN', 'call_id': call_id, 'context': context,
                        'request_sha256': request_sha, 'request_bytes': len(payload),
                        'method': kwargs.get('method', 'highs'),
                        'solver_soft_time_limit': options.get('time_limit'),
                        'hard_wall_seconds': self.timeout}
                self._event(meta)
                self._start_helper()
                helper_pid = self.process.pid
                child_cpu_before = _child_cpu_seconds(helper_pid)
                self._event({**meta, 'event': 'LP_RUNNING', 'helper_pid': helper_pid})
                deadline = time.monotonic() + self.timeout
                self.process.stdin.write((json.dumps({'call_id': call_id}) + '\n').encode())
                self.process.stdin.flush()
                reply = self._reply(deadline, call_id)
                if reply.get('status') != 'DONE':
                    raise RuntimeError('Solver child rejected call: ' + reply.get('error', repr(reply)))
                output = (self.folder / 'result.pkl').read_bytes()
                if len(output) > self.max_request_bytes or _sha(output) != reply['result_sha256']:
                    raise RuntimeError('Solver output byte identity or size differs')
                envelope = pickle.loads(output)
                if envelope['call_id'] != call_id:
                    raise RuntimeError('Solver output call binding differs')
                self.total_solver_cpu_seconds += envelope['solver_cpu_seconds']
                result = envelope['result']
                self.returned_calls += 1
                self.successful_results += int(bool(result.success))
                self._event({'event': 'LP_RETURNED', 'call_id': call_id, 'context': context,
                             'helper_pid': helper_pid, 'success': bool(result.success),
                             'solver_status': int(result.status),
                             'wall_seconds': time.monotonic() - begin,
                             'solver_cpu_seconds': envelope['solver_cpu_seconds'],
                             'total_solver_cpu_seconds': self.total_solver_cpu_seconds})
                if self.returned_calls % 256 == 0:
                    self._event({'event': 'LP_CALL_SUMMARY', 'call_id': call_id,
                                 'returned_calls': self.returned_calls,
                                 'successful_results': self.successful_results,
                                 'unsuccessful_results': self.returned_calls - self.successful_results,
                                 'timeouts': self.timeout_count, 'failures': self.failure_count,
                                 'total_solver_cpu_seconds': self.total_solver_cpu_seconds}, active=False)
                return result
            except GuardDeadline as exc:
                self.timeout_count += 1
                if self.process is not None:
                    helper_pid = self.process.pid
                child_cpu_after = _child_cpu_seconds(helper_pid)
                failed_cpu = (max(0, child_cpu_after - child_cpu_before)
                              if child_cpu_after is not None and child_cpu_before is not None else None)
                if failed_cpu is not None:
                    self.total_solver_cpu_seconds += failed_cpu
                self._stop_helper()
                reason = 'HARD_TIMEOUT: ' + str(exc)
                try:
                    self._retain_failure(call_id, context, reason, helper_pid, request_written, request_sha, failed_cpu)
                except OSError as io_error:
                    self._event({'event': 'FAILURE_RETENTION_ERROR', 'call_id': call_id, 'error': repr(io_error)})
                return _failed_result('LP_GUARD ' + reason)
            except (OSError, RuntimeError, ValueError, EOFError, pickle.PickleError) as exc:
                if self.process is not None:
                    helper_pid = self.process.pid
                child_cpu_after = _child_cpu_seconds(helper_pid)
                failed_cpu = (max(0, child_cpu_after - child_cpu_before)
                              if child_cpu_after is not None and child_cpu_before is not None else None)
                if failed_cpu is not None:
                    self.total_solver_cpu_seconds += failed_cpu
                self._stop_helper()
                reason = 'SOLVER_CALL_ERROR: ' + repr(exc)
                try:
                    self._retain_failure(call_id, context, reason, helper_pid, request_written, request_sha, failed_cpu)
                except OSError as io_error:
                    self._event({'event': 'FAILURE_RETENTION_ERROR', 'call_id': call_id, 'error': repr(io_error)})
                return _failed_result('LP_GUARD ' + reason)
            except BaseException:
                # UserStop/KeyboardInterrupt/SystemExit must propagate. Never
                # convert a stop request into an ordinary failed LP proposal.
                self._stop_helper()
                raise


def install(folder, **options):
    """Install before importing proposal, or patch its existing direct reference."""
    from scipy import optimize
    if getattr(optimize.linprog, '_rho5_lp_guard', None) is not None:
        raise RuntimeError('An LP guard is already installed in this search worker')
    guard = LPGuard(folder, **options)
    def protected(*args, **kwargs):
        return guard.linprog(*args, **kwargs)
    protected._rho5_lp_guard = guard
    optimize.linprog = protected
    proposal = sys.modules.get('proposal')
    if proposal is not None and hasattr(proposal, 'linprog'):
        proposal.linprog = protected
    return guard


def _server(folder, memory_limit, max_payload, toy=False):
    import resource
    folder = Path(folder).resolve()
    for name in THREAD_ENV:
        os.environ[name] = '1'
    if sys.platform.startswith('linux'):
        # Avoid orphaned, still-busy native solvers if the search parent dies.
        import ctypes
        parent_pid = os.getppid()
        if ctypes.CDLL(None, use_errno=True).prctl(1, signal.SIGKILL) != 0:
            raise OSError(ctypes.get_errno(), 'Cannot install solver parent-death signal')
        if parent_pid == 1 or os.getppid() != parent_pid:
            raise SystemExit('Search parent exited during solver setup')
    if not toy:
        resource.setrlimit(resource.RLIMIT_AS, (memory_limit, memory_limit))
        os.nice(max(0, 10 - os.getpriority(os.PRIO_PROCESS, 0)))
    # Native solver diagnostics cannot corrupt the small JSON control channel.
    control = os.dup(sys.stdout.fileno())
    with (folder / 'SOLVER.log').open('ab', buffering=0) as log:
        os.dup2(log.fileno(), sys.stdout.fileno())
        os.dup2(log.fileno(), sys.stderr.fileno())
    def reply(value):
        os.write(control, (json.dumps(value, separators=(',', ':')) + '\n').encode())
    try:
        if not toy:
            from scipy.optimize import linprog as original
        reply({'status': 'READY', 'pid': os.getpid()})
        for line in sys.stdin.buffer:
            control_request = json.loads(line)
            call_id = control_request['call_id']
            try:
                raw = (folder / 'request.pkl').read_bytes()
                if len(raw) > max_payload:
                    raise ValueError('Oversized solver input')
                request = pickle.loads(raw)
                if request['call_id'] != call_id:
                    raise ValueError('Solver input call binding differs')
                args, kwargs = request['args'], dict(request['kwargs'])
                begin = time.process_time()
                if toy:
                    delay = kwargs.pop('_toy_delay', 0)
                    if kwargs.pop('_toy_crash', False):
                        os._exit(31)
                    time.sleep(delay)
                    result = SimpleNamespace(success=True, status=0, fun=1.25, x=[0.5])
                else:
                    method = kwargs.get('method', 'highs')
                    if isinstance(method, str) and method.startswith('highs'):
                        options = dict(kwargs.get('options') or {})
                        options['threads'] = 1
                        # Existing 1/2-second soft limits are preserved. Calls
                        # without one receive 2 seconds plus the parent hard cap.
                        options.setdefault('time_limit', 2.0)
                        kwargs['options'] = options
                    result = original(*args, **kwargs)
                response = pickle.dumps({'call_id': call_id, 'result': result,
                                         'solver_cpu_seconds': time.process_time() - begin}, protocol=5)
                if len(response) > max_payload:
                    raise ValueError('Oversized solver result')
                _atomic_bytes(folder / 'result.pkl', response)
                reply({'status': 'DONE', 'call_id': call_id, 'result_sha256': _sha(response)})
            except BaseException:
                error = traceback.format_exc()[-8192:]
                print(error, file=sys.stderr, flush=True)
                reply({'status': 'ERROR', 'call_id': call_id, 'error': error})
    except BaseException:
        try:
            reply({'status': 'STARTUP_ERROR', 'error': traceback.format_exc()[-8192:]})
        finally:
            raise


def self_test():
    """IPC/deadline controls only, no SciPy import and no mathematical replay."""
    import tempfile
    controls = []
    with tempfile.TemporaryDirectory(prefix='rho5-lp-guard-controls-') as td:
        guard = LPGuard(td, hard_timeout_seconds=0.15, startup_timeout_seconds=5,
                        _toy_server=True, retained_failures=2)
        parent = os.getpid()
        try:
            first = guard.linprog([1])
            helper = guard.process.pid
            second = guard.linprog([2])
            assert first.success and second.success and first.fun == 1.25
            assert guard.process.pid == helper and os.getpid() == parent
            controls.append('successful_results_and_persistent_child')
            begin = time.monotonic()
            timed = guard.linprog([3], _toy_delay=2)
            assert not timed.success and guard.timeout_count == 1
            assert time.monotonic() - begin < 1.5 and guard.process is None
            assert list((Path(td) / 'failed_calls').glob('*.pkl'))
            assert os.getpid() == parent
            controls.append('hard_timeout_only_kills_solver_and_retains_input')
            recovered = guard.linprog([4])
            assert recovered.success and guard.process.pid != helper
            controls.append('next_call_uses_new_solver_same_search_process')
            crashed = guard.linprog([5], _toy_crash=True)
            assert not crashed.success and guard.process is None
            controls.append('solver_crash_becomes_failed_proposal')
            assert guard.linprog([6]).success
            controls.append('successful_recovery_after_solver_crash')
        finally:
            guard.close()
    return {'status': 'PASS', 'controls': controls,
            'scientific_imports': False, 'mathematical_replay': False}


if __name__ == '__main__':
    if len(sys.argv) >= 2 and sys.argv[1] in ('--server', '--toy-server'):
        _server(sys.argv[2], int(sys.argv[3]), int(sys.argv[4]), sys.argv[1] == '--toy-server')
    elif len(sys.argv) == 2 and sys.argv[1] == '--self-test':
        print(json.dumps(self_test(), indent=2))
    else:
        raise SystemExit('Import install/LPGuard, or use --self-test for non-mathematical controls')
